# Crawling Web PTA Trunojoyo

In [ ]:
!pip install requests
!pip install beautifulsoup4
import requests
from bs4 import BeautifulSoup
import pandas as pd

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2025.8.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)

## Fakultas Hukum

### A.Prodi Ilmu Hukum

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def ptaa():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 285):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/1/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("IlmuHukum.csv", index=False)

    return df

In [ ]:
ptaa()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14
📄 Memproses halaman ke-15
📄 Memproses halaman ke-16
📄 Memproses halaman ke-17
📄 Memproses halaman ke-18
📄 Memproses halaman ke-19
📄 Memproses halaman ke-20
📄 Memproses halaman ke-21
📄 Memproses halaman ke-22
📄 Memproses halaman ke-23
📄 Memproses halaman ke-24
📄 Memproses halaman ke-25
📄 Memproses halaman ke-26
📄 Memproses halaman ke-27
📄 Memproses halaman ke-28
📄 Memproses halaman ke-29
📄 Memproses halaman ke-30
📄 Memproses halaman ke-31
📄 Memproses halaman ke-32
📄 Memproses halaman ke-33
📄 Memproses halaman ke-34
📄 Memproses halaman ke-35
📄 Memproses halaman ke-36
📄 Memproses halaman ke-37
📄 Memproses halaman ke-38
📄 Memproses halaman ke-39
📄 Memproses halaman ke-40
📄 Memproses halaman ke-41
📄 Memproses halaman ke-42
📄 Memproses halaman ke-43
📄 Memproses halaman ke-44
📄 Memproses halaman ke-45
📄 Memproses halaman ke-46
📄 Memproses halaman ke-47
📄 Memproses halaman ke-48
📄 Memproses halaman ke-49
📄 Memproses halaman ke-50
📄 Memproses halaman ke-51
📄 Memproses halaman ke-52
📄 Memproses halaman ke-53
📄 Memproses halaman ke-54
📄 Memproses halaman ke-55
📄 Memproses halaman ke-56
📄 Memproses halaman ke-57
📄 Memproses halaman ke-58
📄 Memproses halaman ke-59
📄 Memproses halaman ke-60
📄 Memproses halaman ke-61
📄 Memproses halaman ke-62
📄 Memproses halaman ke-63
📄 Memproses halaman ke-64
📄 Memproses halaman ke-65
📄 Memproses halaman ke-66
📄 Memproses halaman ke-67
📄 Memproses halaman ke-68
📄 Memproses halaman ke-69
📄 Memproses halaman ke-70
📄 Memproses halaman ke-71
📄 Memproses halaman ke-72
📄 Memproses halaman ke-73
📄 Memproses halaman ke-74
📄 Memproses halaman ke-75
📄 Memproses halaman ke-76
📄 Memproses halaman ke-77
📄 Memproses halaman ke-78
📄 Memproses halaman ke-79
📄 Memproses halaman ke-80
📄 Memproses halaman ke-81
📄 Memproses halaman ke-82
📄 Memproses halaman ke-83
📄 Memproses halaman ke-84
📄 Memproses halaman ke-85
📄 Memproses halaman ke-86
📄 Memproses halaman ke-87
📄 Memproses halaman ke-88
📄 Memproses halaman ke-89
📄 Memproses halaman ke-90
📄 Memproses halaman ke-91
📄 Memproses halaman ke-92
📄 Memproses halaman ke-93
📄 Memproses halaman ke-94
📄 Memproses halaman ke-95
📄 Memproses halaman ke-96
📄 Memproses halaman ke-97
📄 Memproses halaman ke-98
📄 Memproses halaman ke-99
📄 Memproses halaman ke-100
📄 Memproses halaman ke-101
📄 Memproses halaman ke-102
📄 Memproses halaman ke-103
📄 Memproses halaman ke-104
📄 Memproses halaman ke-105
📄 Memproses halaman ke-106
📄 Memproses halaman ke-107
📄 Memproses halaman ke-108
📄 Memproses halaman ke-109
📄 Memproses halaman ke-110
📄 Memproses halaman ke-111
📄 Memproses halaman ke-112
📄 Memproses halaman ke-113
📄 Memproses halaman ke-114
📄 Memproses halaman ke-115
📄 Memproses halaman ke-116
📄 Memproses halaman ke-117
📄 Memproses halaman ke-118
📄 Memproses halaman ke-119
📄 Memproses halaman ke-120
📄 Memproses halaman ke-121
📄 Memproses halaman ke-122
📄 Memproses halaman ke-123
📄 Memproses halaman ke-124
📄 Memproses halaman ke-125
📄 Memproses halaman ke-126
📄 Memproses halaman ke-127
📄 Memproses halaman ke-128
📄 Memproses halaman ke-129
📄 Memproses halaman ke-130
📄 Memproses halaman ke-131
📄 Memproses halaman ke-132
📄 Memproses halaman ke-133
📄 Memproses halaman ke-134
📄 Memproses halaman ke-135
📄 Memproses halaman ke-136
📄 Memproses halaman ke-137
📄 Memproses halaman ke-138
📄 Memproses halaman ke-139
📄 Memproses halaman ke-140
📄 Memproses halaman ke-141
📄 Memproses halaman ke-142
📄 Memproses halaman ke-143
📄 Memproses halaman ke-144
📄 Memproses halaman ke-145
📄 Memproses halaman ke-146
📄 Memproses halaman ke-147
📄 Memproses halaman ke-148
📄 Memproses halaman ke-149
📄 Memproses halaman ke-150
📄 Memproses halaman ke-151
📄 Memproses halaman ke-152
📄 Memproses halaman ke-153
📄 Memproses halaman ke-154
📄 Memproses halaman ke-155
📄 Memproses halaman ke-156
📄 Memproses halaman ke-157
📄 Memproses halaman ke-158
📄 Memproses halaman ke-159
📄 Memproses halaman ke-160
📄 Memproses halaman ke-161
📄 Memproses halaman ke-162
📄 Memproses halaman ke-163
📄 Memproses halaman ke-164
📄 Memproses halaman ke-165
📄 Memproses halaman ke-166
📄 Memproses halaman ke-167
📄 Memproses halaman ke-168
📄 Memproses halaman ke-169
📄 Memproses halaman ke-170
📄 Memproses halaman ke-171
📄 Memproses halaman ke-172
📄 Memproses halaman ke-173
📄 Memproses halaman ke-174
📄 Memproses halaman ke-175
📄 Memproses halaman ke-176
📄 Memproses halaman ke-177
📄 Memproses halaman ke-178
📄 Memproses halaman ke-179
📄 Memproses halaman ke-180
📄 Memproses halaman ke-181
📄 Memproses halaman ke-182
📄 Memproses halaman ke-183
📄 Memproses halaman ke-184
📄 Memproses halaman ke-185
📄 Memproses halaman ke-186
📄 Memproses halaman ke-187
📄 Memproses halaman ke-188
📄 Memproses halaman ke-189
📄 Memproses halaman ke-190
📄 Memproses halaman ke-191
📄 Memproses halaman ke-192
📄 Memproses halaman ke-193
📄 Memproses halaman ke-194
📄 Memproses halaman ke-195
📄 Memproses halaman ke-196
📄 Memproses halaman ke-197
📄 Memproses halaman ke-198
📄 Memproses halaman ke-199
📄 Memproses halaman ke-200
📄 Memproses halaman ke-201
📄 Memproses halaman ke-202
📄 Memproses halaman ke-203
📄 Memproses halaman ke-204
📄 Memproses halaman ke-205
📄 Memproses halaman ke-206
📄 Memproses halaman ke-207
📄 Memproses halaman ke-208
📄 Memproses halaman ke-209
📄 Memproses halaman ke-210
📄 Memproses halaman ke-211
📄 Memproses halaman ke-212
📄 Memproses halaman ke-213
📄 Memproses halaman ke-214
📄 Memproses halaman ke-215
📄 Memproses halaman ke-216
📄 Memproses halaman ke-217
📄 Memproses halaman ke-218
📄 Memproses halaman ke-219
📄 Memproses halaman ke-220
📄 Memproses halaman ke-221
📄 Memproses halaman ke-222
📄 Memproses halaman ke-223
📄 Memproses halaman ke-224
📄 Memproses halaman ke-225
📄 Memproses halaman ke-226
📄 Memproses halaman ke-227
📄 Memproses halaman ke-228
📄 Memproses halaman ke-229
📄 Memproses halaman ke-230
📄 Memproses halaman ke-231
📄 Memproses halaman ke-232
📄 Memproses halaman ke-233
📄 Memproses halaman ke-234
📄 Memproses halaman ke-235
📄 Memproses halaman ke-236
📄 Memproses halaman ke-237
📄 Memproses halaman ke-238
📄 Memproses halaman ke-239
📄 Memproses halaman ke-240
📄 Memproses halaman ke-241
📄 Memproses halaman ke-242
📄 Memproses halaman ke-243
📄 Memproses halaman ke-244
📄 Memproses halaman ke-245
📄 Memproses halaman ke-246
📄 Memproses halaman ke-247
📄 Memproses halaman ke-248
📄 Memproses halaman ke-249
📄 Memproses halaman ke-250
📄 Memproses halaman ke-251
📄 Memproses halaman ke-252
📄 Memproses halaman ke-253
📄 Memproses halaman ke-254
📄 Memproses halaman ke-255
📄 Memproses halaman ke-256
📄 Memproses halaman ke-257
📄 Memproses halaman ke-258
📄 Memproses halaman ke-259
📄 Memproses halaman ke-260
📄 Memproses halaman ke-261
📄 Memproses halaman ke-262
📄 Memproses halaman ke-263
📄 Memproses halaman ke-264
📄 Memproses halaman ke-265
📄 Memproses halaman ke-266
📄 Memproses halaman ke-267
📄 Memproses halaman ke-268
📄 Memproses halaman ke-269
📄 Memproses halaman ke-270
📄 Memproses halaman ke-271
📄 Memproses halaman ke-272
📄 Memproses halaman ke-273
📄 Memproses halaman ke-274
📄 Memproses halaman ke-275
📄 Memproses halaman ke-276
📄 Memproses halaman ke-277
📄 Memproses halaman ke-278
📄 Memproses halaman ke-279
📄 Memproses halaman ke-280
📄 Memproses halaman ke-281
📄 Memproses halaman ke-282
📄 Memproses halaman ke-283
📄 Memproses halaman ke-284

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Dyah Ayu Citra Seza,Implementasi Fungsi Legislasi Dewan Perwakilan...,"Yudi Widagdo Harimurti, SH., MH","Safi', SH., MH",ABSTRAK\r\n\r\n Implementasi Fungsi Legi...,ABSTRACT\r\n Implementation of Legislati...
1,Maulina Nurlaily,Pertanggungjawaban Pidana Direksi BUMN (Perser...,"Tolib Effendi, SH., MH.","Dr. Eni Suastuti, SH., Mhum.",Badan Usaha Milik Negara (BUMN) adalah Badan u...,State Owned Enterprises (SOEs) are business en...
2,Moh. Samsul Hidayat,Analisis Terhadap Kekosongan Hukum dalam Penga...,"Tolib Effendi, SH., MH.","Agus Ramdlany, SH., MH.",Kasus narkoba tidak henti-hentinya terdengar d...,"Drug cases endlessly heard on television, radi..."
3,TOMMY ADITYA PARLINDUNGAN MARBUN,PERLINDUNGAN HUKUM BAGI KONSUMEN ATAS PRODUK E...,"DR. DJULAEKA, S.H., M.HUM","DR.USWATUN HASANAH, S.H., M. HUM",Produk elektronik adalah suatu benda bergerak ...,Electronic products is an object moves through...
4,RICA YENA IMADHORA,TELAAH KRITIS TENTANG ALASAN HUKUM YANG DIGUN...,"Dr. DENI SBY, S. H., M. S.","SAIFUL ABDULLAH, S. H., M. H.",,
...,...,...,...,...,...,...
1412,DEDY DORES,PENGKUALIFIKASIAN CHEATER SEBAGAI TINDAK PIDAN...,"Aris Hardinanto, S.H., M.H.",,Abstrak\n Perbuatan cheater dalam melakukan ch...,Abstract\n The way of cheater did a cheat in o...
1413,Eko Supriadi,KUALIFIKASI TINDAK PIDANA ATAS PERBUATAN PELAK...,"Dr. Erma Rusdiana, S.H.,M.H",,Peminjaman dana sistem online dilakukan oleh m...,The loan funds by online system are carried ou...
1414,Muslimatul Maghfirah,KEDUDUKAN HUKUM PEKERJA OUTSOURCING DI DINAS P...,"Mishbahul Munir, S.H., M.Hum",,Abstrak\nTenaga kerja merupakan setiap orang y...,Abstract\nLabors are those who can work to pro...
1415,MOH WASIL SYAHRONI,STAGNANSI HUBUNGAN KELEMBAGAAN DAN KEWENANGAN ...,"Dr. DENI SETYA BAGUS YUHERAWAN, S.H., M.S",,Skripsi ini bertujuan untuk menganalisis penti...,This thesis aims to analyze the stagnation of ...
1416,Moch. Steven,PERUMUSAN SANKSI PIDANA BAGI MASYARAKAT SEKITA...,"Dr. Wartiningsih, S.H., M.Hum",,ABSTRAK\nAkhir-akhir ini semakin maraknya penc...,"ABSTRACK\nLately, there has been more and more..."

### B.Prodi Magister Ilmu Hukum

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def mhukum():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 15):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/24/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("mhukum.csv", index=False)
A
    return df

In [ ]:
mhukum()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,MOCHAMAD SAICHU,PERTANGGUNG JAWABAN HUKUM PEJABAT PEMBUAT KOMI...,"Dr. Nunuk Nuswardani S.H., M.H","Dr. Deni SB Yuherawan S.H., Msi",Korupsi tergolong ke dalam kejahatan yang l...,Korupsi tergolong ke dalam kejahatan yang l...
1,"nanang hariansah, SH",KARAKTERISTIK KONTRAK PEMERINTAH PENGADAAN BAR...,"Dr. DJULAEKA, SH., M.Hum","Dr. MURNI, SH., M.Hum",Kontrak pengadaan barang/jasa pemerintah adala...,Government goods/service supplying contractt i...
2,SOELISTIJONO,PEMBERHENTIAN TIDAK DENGAN HORMAT BAGI ANGGOTA...,"Dr. MUFARRIJUL IKHWAN, S.H., M.Hum.","Dr. NUNUK NUSWARDANI, S.H., M.H",ABSTRAKSI\r\n\r\nPEMBERHENTIAN TIDAK DENGAN HO...,ABSTRACT\r\n\r\nDISMISSAL NOT WITH RESPECT TO ...
3,"DIAH TRI SETIANINGSIH,S.H",KONSEP ANAK YANG BERKONFLIK DENGAN HUKUM DALAM...,"Dr. Deni SB Yuherawan,S.H.,MS","Dr. Wartiningsih, S.H., Mhum",Sistem Peradilan Pidana Anak saat ini telah me...,Juvenile Criminal Justice System today has und...
4,WAHYUDI,PENATAGUNAAN TANAH DALAM UPAYA OPTIMALISASI PE...,"Dr. Mufarrijul Ikhwan, SH.,MHum","Dr. Indien Winarwati, SH.,MH",Keberadaan tanah merupakan hal yang sangat pen...,The existence of the soil is very important fo...
...,...,...,...,...,...,...
63,HAMIDI,KEWENANGAN KANTOR PERTANAHAN DALAM MENYELESAIK...,"Dr. Indien Winarwati, S.H., M.H","Dr. Djulaeka, S.H., M.Hum",Permasalahan sengketa pertanahan merupakan mas...,The issue of land disputes is a complex issue ...
64,Ach. Eli Fadlal,MENYETUBUHI MAYAT DALAM PERSPEKTIF HUKUM PIDAN...,"Dr. Erma Rusdiana., S.H., M.H.","Dr. Eny Suastuti., SH., M. Hum",ABSTRAK\n\nMenyetubuhi dapat didefinisikan seb...,ABSTRACT\n\nIntercourse can be defined as sexu...
65,"Iwan Santoso, S.H.",ANALISA HUKUM SELEKSI PENERIMAAN APARATUR\nSIP...,"Dr. Yudi Widagdo Harimurti., S.H., M.H.","Dr. Wartiningsih., SH., M. Hum",Aparatur Sipil Negara adalah profesi bagi pega...,The State Civil Apparatus is a profession for ...
66,"BUNTORO, S.H",Penyelesaian Tindak Pidana yang Dilatarbelakan...,"Dr. Deny Setya Bagus Yuherawan, S.H.,M.S","Dr. Syamsul Fatoni, S.H.,M.H.",Pasal 28E ayat (1) Undang-Undang Dasar Negara ...,Article 28E paragraph (1) of the Constitution ...
67,Rachmad Hidayat,ASPEK HUKUM KEWENANGAN PENGEMBANGAN KAWASAN IN...,"Dr. Safi, SH, MH","Dr. Nuruz Zaman, SH, MH",Research conducted in this thesis is normative...,Research conducted in this thesis is normative...

## Fakultas Pertanian

### A.Prodi Teknologi Industri Pertanian

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def tip():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 115):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/2/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("TIP.csv", index=False)

    return df

In [ ]:
tip()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14
📄 Memproses halaman ke-15
📄 Memproses halaman ke-16
📄 Memproses halaman ke-17
📄 Memproses halaman ke-18
📄 Memproses halaman ke-19
📄 Memproses halaman ke-20
📄 Memproses halaman ke-21
📄 Memproses halaman ke-22
📄 Memproses halaman ke-23
📄 Memproses halaman ke-24
📄 Memproses halaman ke-25
📄 Memproses halaman ke-26
📄 Memproses halaman ke-27
📄 Memproses halaman ke-28
📄 Memproses halaman ke-29
📄 Memproses halaman ke-30
📄 Memproses halaman ke-31
📄 Memproses halaman ke-32
📄 Memproses halaman ke-33
📄 Memproses halaman ke-34
📄 Memproses halaman ke-35
📄 Memproses halaman ke-36
📄 Memproses halaman ke-37
📄 Memproses halaman ke-38
📄 Memproses halaman ke-39
📄 Memproses halaman ke-40
📄 Memproses halaman ke-41
📄 Memproses halaman ke-42
📄 Memproses halaman ke-43
📄 Memproses halaman ke-44
📄 Memproses halaman ke-45
📄 Memproses halaman ke-46
📄 Memproses halaman ke-47
📄 Memproses halaman ke-48
📄 Memproses halaman ke-49
📄 Memproses halaman ke-50
📄 Memproses halaman ke-51
📄 Memproses halaman ke-52
📄 Memproses halaman ke-53
📄 Memproses halaman ke-54
📄 Memproses halaman ke-55
📄 Memproses halaman ke-56
📄 Memproses halaman ke-57
📄 Memproses halaman ke-58
📄 Memproses halaman ke-59
📄 Memproses halaman ke-60
📄 Memproses halaman ke-61
📄 Memproses halaman ke-62
📄 Memproses halaman ke-63
📄 Memproses halaman ke-64
📄 Memproses halaman ke-65
📄 Memproses halaman ke-66
📄 Memproses halaman ke-67
📄 Memproses halaman ke-68
📄 Memproses halaman ke-69
📄 Memproses halaman ke-70
📄 Memproses halaman ke-71
📄 Memproses halaman ke-72
📄 Memproses halaman ke-73
📄 Memproses halaman ke-74
📄 Memproses halaman ke-75
📄 Memproses halaman ke-76
📄 Memproses halaman ke-77
📄 Memproses halaman ke-78
📄 Memproses halaman ke-79
📄 Memproses halaman ke-80
📄 Memproses halaman ke-81
📄 Memproses halaman ke-82
📄 Memproses halaman ke-83
📄 Memproses halaman ke-84
📄 Memproses halaman ke-85
📄 Memproses halaman ke-86
📄 Memproses halaman ke-87
📄 Memproses halaman ke-88
📄 Memproses halaman ke-89
📄 Memproses halaman ke-90
📄 Memproses halaman ke-91
📄 Memproses halaman ke-92
📄 Memproses halaman ke-93
📄 Memproses halaman ke-94
📄 Memproses halaman ke-95
📄 Memproses halaman ke-96
📄 Memproses halaman ke-97
📄 Memproses halaman ke-98
📄 Memproses halaman ke-99
📄 Memproses halaman ke-100
📄 Memproses halaman ke-101
📄 Memproses halaman ke-102
📄 Memproses halaman ke-103
📄 Memproses halaman ke-104
📄 Memproses halaman ke-105
📄 Memproses halaman ke-106
📄 Memproses halaman ke-107
📄 Memproses halaman ke-108
📄 Memproses halaman ke-109
📄 Memproses halaman ke-110
📄 Memproses halaman ke-111
📄 Memproses halaman ke-112
📄 Memproses halaman ke-113
📄 Memproses halaman ke-114

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Mojiono,Sifat Fisik dan Profil Gelatinisasi Tepung Uwi...,"Ir. Umi Purwandari, M.App.Sc., Ph.D","Burhan, S.TP., MT",Teknologi modifikasi pada tepung non konvensio...,Starch modification technology has a potential...
1,Rudiyana Maf 'Ulah,PENGARUH KONSENTRASI FLOKULAN (MAGNAFLOC LT 27...,"Darimiyya Hidayati, S.TP. MP.","Ir. Muhammad Fakhry, MP.",Kualitas gula yang dihasilkan tergantung pada ...,The quality of sugar produced depends on the q...
2,Indah Purnama Sari,Optimasi Penggunaan Tepung Labu Kuning dan Gum...,Dr. Umi Purwandari,"Supriyanto, S.TP.,M.P",Program diversifikasi bahan pangan lokal dihar...,Local food diversification program is expected...
3,Ahmad Fawaid Kurniawan,Kondisi Optimum Pembuatan Cup Cake Tersubstitu...,Dr. Umi Purwandari,"Burhan S.TP, M.T",ABSTRAK\r\nBahan pangan lokal yang dapat mensu...,ABSTRACT\r\nTaro which has high carbohydrate c...
4,Mohammad Osidani Aji Wijaya,ANALISIS FINANSIAL PADA PRODUKSI ROTI TAWAR ME...,"Banun Dyah Probowati S.TP, Msi",Dr. Umi Purwandari,ABSTRAK\r\n\r\n\r\nRoti tawar merupakan makana...,Abstract\r\n\r\nBread is a popular food which ...
...,...,...,...,...,...,...
563,MUHAMMAD RIZAL,PENGENDALIAN KUALITAS TEMBAKAU KERING DENGAN ...,"Dr. M. Fuad Fauzul M, STP., M.Si","Ir. Moh. Fakhry., MP",Pengendalian kualitas merupakan sebuah upaya u...,Quality control is an effort to maintain and i...
564,ACHMAD ARDI WIJAYA,PENGEMBANGAN PRODUK KERUPUK AMPLANG DENGAN PEN...,"Dr. Moh. Fuad Fauzul M, S.TP., M.Si","Khoirul Hidayat, ST., MT",Produk ramah lingkungan dapat mengurangi terja...,Environmentally friendly products can reduce t...
565,Hendriyadi,Analisis Faktor Yang Mempengaruhi Pembelian Te...,"Dr. Moh. Fuad Fauzul M, S.TP., M.Si","Khoirul Hidayat, ST.,MT",UD. Dianis merupakan industri rumah tangga yan...,UD. Dianis is a home industry that produces tr...
566,Peni Asrurin,Karakteristik Fisik dan Sensoris Mi Kering Tep...,"Ir. Umi Purwandari, M.App.Sc., Ph.D.","Cahyo Indarto, S.TP., M.P",ABSTRAK\n\n\n Mi merupakan makanan yang sudah ...,ABSTRACT\n\n\nNoodles are foods that commonly ...
567,Budiyono,ALTERNATIF PEMILIHAN JENIS PAKAN SAPI MADURA D...,"Dr, Muhammad fuad FM,STP.M.Si","Dr.Ir. H.Asfan,MP",Abstrak\n Dalam menyediakan hijauan pakan tern...,Abstract\nIn providing forage forage must be k...

### B.Prodi Agribisnis

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def agribisnis():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 111):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/3/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("agribisnis.csv", index=False)

    return df

In [ ]:
agribisnis()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14
📄 Memproses halaman ke-15
📄 Memproses halaman ke-16
📄 Memproses halaman ke-17
📄 Memproses halaman ke-18
📄 Memproses halaman ke-19
📄 Memproses halaman ke-20
📄 Memproses halaman ke-21
📄 Memproses halaman ke-22
📄 Memproses halaman ke-23
📄 Memproses halaman ke-24
📄 Memproses halaman ke-25
📄 Memproses halaman ke-26
📄 Memproses halaman ke-27
📄 Memproses halaman ke-28
📄 Memproses halaman ke-29
📄 Memproses halaman ke-30
📄 Memproses halaman ke-31
📄 Memproses halaman ke-32
📄 Memproses halaman ke-33
📄 Memproses halaman ke-34
📄 Memproses halaman ke-35
📄 Memproses halaman ke-36
📄 Memproses halaman ke-37
📄 Memproses halaman ke-38
📄 Memproses halaman ke-39
📄 Memproses halaman ke-40
📄 Memproses halaman ke-41
📄 Memproses halaman ke-42
📄 Memproses halaman ke-43
📄 Memproses halaman ke-44
📄 Memproses halaman ke-45
📄 Memproses halaman ke-46
📄 Memproses halaman ke-47
📄 Memproses halaman ke-48
📄 Memproses halaman ke-49
📄 Memproses halaman ke-50
📄 Memproses halaman ke-51
📄 Memproses halaman ke-52
📄 Memproses halaman ke-53
📄 Memproses halaman ke-54
📄 Memproses halaman ke-55
📄 Memproses halaman ke-56
📄 Memproses halaman ke-57
📄 Memproses halaman ke-58
📄 Memproses halaman ke-59
📄 Memproses halaman ke-60
📄 Memproses halaman ke-61
📄 Memproses halaman ke-62
📄 Memproses halaman ke-63
📄 Memproses halaman ke-64
📄 Memproses halaman ke-65
📄 Memproses halaman ke-66
📄 Memproses halaman ke-67
📄 Memproses halaman ke-68
📄 Memproses halaman ke-69
📄 Memproses halaman ke-70
📄 Memproses halaman ke-71
📄 Memproses halaman ke-72
📄 Memproses halaman ke-73
📄 Memproses halaman ke-74
📄 Memproses halaman ke-75
📄 Memproses halaman ke-76
📄 Memproses halaman ke-77
📄 Memproses halaman ke-78
📄 Memproses halaman ke-79
📄 Memproses halaman ke-80
📄 Memproses halaman ke-81
📄 Memproses halaman ke-82
📄 Memproses halaman ke-83
📄 Memproses halaman ke-84
📄 Memproses halaman ke-85
📄 Memproses halaman ke-86
📄 Memproses halaman ke-87
📄 Memproses halaman ke-88
📄 Memproses halaman ke-89
📄 Memproses halaman ke-90
📄 Memproses halaman ke-91
📄 Memproses halaman ke-92
📄 Memproses halaman ke-93
📄 Memproses halaman ke-94
📄 Memproses halaman ke-95
📄 Memproses halaman ke-96
📄 Memproses halaman ke-97
📄 Memproses halaman ke-98
📄 Memproses halaman ke-99
📄 Memproses halaman ke-100
📄 Memproses halaman ke-101
📄 Memproses halaman ke-102
📄 Memproses halaman ke-103
📄 Memproses halaman ke-104
📄 Memproses halaman ke-105
📄 Memproses halaman ke-106
📄 Memproses halaman ke-107
📄 Memproses halaman ke-108
📄 Memproses halaman ke-109
📄 Memproses halaman ke-110

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,ENDAR PUSPA DESA,PROSPEK USAHA BAKSO IKAN DI PULAU MANDANGIN KA...,"Ihsannudin, SP., MP","Aminah Happy M.A, SP., M.Si",ABSTRAK\r\n\tSalah satu pulau kecil yang memer...,ABSTRACT\r\n\tOne of the small island which ne...
1,Aldiladese Jenri,Analisis Dampak Pola Kemitraan Terhadap Pendap...,"Amanatuz Zuhriyah, SP., MMA","Slamet Widodo, SP., MSi",Tujuan dari penelitian ini adalah untuk menget...,
2,"Aji Sandya Satriyo, SP",Pemanfaatan Modal Sosial Usahatani Tembakau di...,"Slamet Widodo SP, M.Si","Ihsannudin SP, MP",Modal sosial adalah suatu bentuk hubungan sosi...,
3,Prima Noviyanto,ANALISIS PERILAKU KONSUMEN PADA MAHASISWA PERO...,"Slamet Widodo, SP., M.Si","Taufik Rizal Dwi AN, SP., MM",Perilaku konsumen adalah suatu proses keputusa...,The consumer behavior is a decision process be...
4,Abdus Syukur,ANALISIS KELAYAKAN DAN STRATEGI PENGEMBANGAN U...,"Aminah Happy M.A., SP., Msi.","Amanatuz Zuhriyah, SP., MMA.",ABSTRAK\r\n\r\n\r\nKeberadaan Usaha Kecil dan ...,
...,...,...,...,...,...,...
542,Meilinda Sari,Meilinda Sari\n160321100007\nAgribinis,"Novi Diana Badrut Tamami, SP.MP","Dr. Teti Sugiatri,SP.,M.Si",,
543,Chilyatun Nafisah Oktavina,Chilyatun Nafisah Oktavina\n160321100064\nAgri...,"Dr. Teti Sugiarti, SP., M.Si.","Dr. Elys Fauziyah, SP., MP.",,
544,I'ANATUS SHOFIYAH,I'ANATUS SHOFIYAH;160321100035;AGRIBISNIS,"Dr. Teti Sugiarti, SP., M.Si.","Andrie K Sunyigono, SP., MP., Ph.D.",I'ANATUS SHOFIYAH;160321100035;AGRIBISNIS,I'ANATUS SHOFIYAH;160321100035;AGRIBISNIS
545,Lilis Nur Azizah,Lilis Nur Azizah\n160321100038\nAgribisnis,"Dr. Teti Sugiarti, S.P., M.Si","Dr. Mardiyah Hayati, S.P., M.P",,
546,farida,Farida\n18 juni 2020\n160321100052\nAgribisnis,"Dr. Elys Fauziyah, SP,. MP","Amanatuz Zuhriyah, SP,. MMA",,

### C.Prodi Agroteknologi

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def agroteknologi():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 117):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/4/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("agroteknologi.csv", index=False)

    return df

In [ ]:
agroteknologi()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14
📄 Memproses halaman ke-15
📄 Memproses halaman ke-16
📄 Memproses halaman ke-17
📄 Memproses halaman ke-18
📄 Memproses halaman ke-19
📄 Memproses halaman ke-20
📄 Memproses halaman ke-21
📄 Memproses halaman ke-22
📄 Memproses halaman ke-23
📄 Memproses halaman ke-24
📄 Memproses halaman ke-25
📄 Memproses halaman ke-26
📄 Memproses halaman ke-27
📄 Memproses halaman ke-28
📄 Memproses halaman ke-29
📄 Memproses halaman ke-30
📄 Memproses halaman ke-31
📄 Memproses halaman ke-32
📄 Memproses halaman ke-33
📄 Memproses halaman ke-34
📄 Memproses halaman ke-35
📄 Memproses halaman ke-36
📄 Memproses halaman ke-37
📄 Memproses halaman ke-38
📄 Memproses halaman ke-39
📄 Memproses halaman ke-40
📄 Memproses halaman ke-41
📄 Memproses halaman ke-42
📄 Memproses halaman ke-43
📄 Memproses halaman ke-44
📄 Memproses halaman ke-45
📄 Memproses halaman ke-46
📄 Memproses halaman ke-47
📄 Memproses halaman ke-48
📄 Memproses halaman ke-49
📄 Memproses halaman ke-50
📄 Memproses halaman ke-51
📄 Memproses halaman ke-52
📄 Memproses halaman ke-53
📄 Memproses halaman ke-54
📄 Memproses halaman ke-55
📄 Memproses halaman ke-56
📄 Memproses halaman ke-57
📄 Memproses halaman ke-58
📄 Memproses halaman ke-59
📄 Memproses halaman ke-60
📄 Memproses halaman ke-61
📄 Memproses halaman ke-62
📄 Memproses halaman ke-63
📄 Memproses halaman ke-64
📄 Memproses halaman ke-65
📄 Memproses halaman ke-66
📄 Memproses halaman ke-67
📄 Memproses halaman ke-68
📄 Memproses halaman ke-69
📄 Memproses halaman ke-70
📄 Memproses halaman ke-71
📄 Memproses halaman ke-72
📄 Memproses halaman ke-73
📄 Memproses halaman ke-74
📄 Memproses halaman ke-75
📄 Memproses halaman ke-76
📄 Memproses halaman ke-77
📄 Memproses halaman ke-78
📄 Memproses halaman ke-79
📄 Memproses halaman ke-80
📄 Memproses halaman ke-81
📄 Memproses halaman ke-82
📄 Memproses halaman ke-83
📄 Memproses halaman ke-84
📄 Memproses halaman ke-85
📄 Memproses halaman ke-86
📄 Memproses halaman ke-87
📄 Memproses halaman ke-88
📄 Memproses halaman ke-89
📄 Memproses halaman ke-90
📄 Memproses halaman ke-91
📄 Memproses halaman ke-92
📄 Memproses halaman ke-93
📄 Memproses halaman ke-94
📄 Memproses halaman ke-95
📄 Memproses halaman ke-96
📄 Memproses halaman ke-97
📄 Memproses halaman ke-98
📄 Memproses halaman ke-99
📄 Memproses halaman ke-100
📄 Memproses halaman ke-101
📄 Memproses halaman ke-102
📄 Memproses halaman ke-103
📄 Memproses halaman ke-104
📄 Memproses halaman ke-105
📄 Memproses halaman ke-106
📄 Memproses halaman ke-107
📄 Memproses halaman ke-108
📄 Memproses halaman ke-109
📄 Memproses halaman ke-110
📄 Memproses halaman ke-111
📄 Memproses halaman ke-112
📄 Memproses halaman ke-113
📄 Memproses halaman ke-114
📄 Memproses halaman ke-115
📄 Memproses halaman ke-116

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Yusriansyah,"Efektifitas Pemberian Nutrisi Air Leri, Air Ke...","Dr. Ir. H. Ahmad Arsyadmunir, MS","Ir. Sinar Suryawati, MSi",Yusriansyah. 08.03.1.1.1.00005. Efektifitas Pe...,Yusriansyah. 08.03.1.1.1.00005. Provision of W...
1,Nurhayati,RESPON PERTUMBUHAN VEGETATIF TANAMAN HIAS ILER...,"Mustika Tripatmasari, SP.,MSi","Catur Wasonowati, SP.,MSi",ABSTRAK\r\n\r\nIler (Coleus blumei) merupakan ...,ABSTRACT\r\n\r\nIler (Coleus scutellarioides ...
2,Balia Perwitasari,Pengaruh Media Tanam Dan Nutrisi Terhadap Pert...,"Mustika Tripatmasari, SP., M.Si.","Catur Wasonowati, SP., M.Si.",Pakchoi (Brassica juncea L.) merupakan salah s...,Pakchoi (Brassica juncea L.). is one kind of a...
3,Adhadiyanto,UJI PUPUK SULFUR TERHADAP PERTUMBUHAN DAN HASI...,"Dr. Ir. RA Sidqi Zaed ZM, MS","Dr. Ir. Eko Murniyanto, MP",Bawang merah merupakan salah satu komoditas un...,Shallot is one commodity that is widely used v...
4,Refkie Ardiansyah,KERAGAMAN KANDUNGAN MINYAK ATSIRI BUAH CABE JA...,Ir. Sinar Suryawati M.Si,Drs.Kaswan Badami M.Si,Cabe jamu (Piper retrofractum Vahl) merupakan ...,Java long pepper (Piper retrofractum Vahl) is ...
...,...,...,...,...,...,...
572,ASIYATUL BADRIYAH,"PENGARUH DOSIS PUPUK N, P, K TERHADAP PERTUMBU...","Ir. AMIN ZUCHRI, MP","Dr. Ir. H. AHMAD ARSYAD MUNIR, M.Si",Permasalahan yang sering ditemui yaitu produks...,The problem that is often encountered is the p...
573,Merliana Dewi Astutik,Respon Pertumbuhan dan Hasil Tanaman Kolesom (...,"Ir. Sinar Suryawati, M.Si","Dr. Agr. Eko Setiawan, S.P., M.Si",ABSTRAK\n\nTanaman Kolesom (Talinum triangular...,ABSTRACT\n\nTalinum triangulare (Jacq.) Willd ...
574,Yeni Novitasari,Respon Tanaman Kolesom (Talinum triangulare (J...,"Ir. Sinar Suryawati, M.Si","Dr. Ir. Eko Murnianto, MP",Tanaman kolesom (Talinum. triangulare (Jacq) W...,Colesom plants (Talinum. Triangulare (Jacq) Wi...
575,Mar'atus Sholihah,Pengaruh Pemberian Pupuk Kandang Sapi Terhadap...,"Ir. Sinar Suryawati,M.Si","Dr. Agr. Eko Setiawan, S.P., M. Si",Penelitian ini bertujuan mengetahui pengaruh p...,The objective of this study was to investigate...
576,Nur Hidayah,Pengaruh Biochar Sekam Padi dan Pupuk Kandang ...,"Ir. Slamet Supriyadi, M.Si","Dr. Ir. Ahmad Arsyad Munir, M.S.",Biochar merupakan padatan yang kaya kandungan ...,Biochar is a material that rich in carbonaceou...

### Ilmu Kelautan

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def kelautan():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 97):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/5/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("kelautan.csv", index=False)

    return df

In [ ]:
kelautan()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14
📄 Memproses halaman ke-15
📄 Memproses halaman ke-16
📄 Memproses halaman ke-17
📄 Memproses halaman ke-18
📄 Memproses halaman ke-19
📄 Memproses halaman ke-20
📄 Memproses halaman ke-21
📄 Memproses halaman ke-22
📄 Memproses halaman ke-23
📄 Memproses halaman ke-24
📄 Memproses halaman ke-25
📄 Memproses halaman ke-26
📄 Memproses halaman ke-27
📄 Memproses halaman ke-28
📄 Memproses halaman ke-29
📄 Memproses halaman ke-30
📄 Memproses halaman ke-31
📄 Memproses halaman ke-32
📄 Memproses halaman ke-33
📄 Memproses halaman ke-34
📄 Memproses halaman ke-35
📄 Memproses halaman ke-36
📄 Memproses halaman ke-37
📄 Memproses halaman ke-38
📄 Memproses halaman ke-39
📄 Memproses halaman ke-40
📄 Memproses halaman ke-41
📄 Memproses halaman ke-42
📄 Memproses halaman ke-43
📄 Memproses halaman ke-44
📄 Memproses halaman ke-45
📄 Memproses halaman ke-46
📄 Memproses halaman ke-47
📄 Memproses halaman ke-48
📄 Memproses halaman ke-49
📄 Memproses halaman ke-50
📄 Memproses halaman ke-51
📄 Memproses halaman ke-52
📄 Memproses halaman ke-53
📄 Memproses halaman ke-54
📄 Memproses halaman ke-55
📄 Memproses halaman ke-56
📄 Memproses halaman ke-57
📄 Memproses halaman ke-58
📄 Memproses halaman ke-59
📄 Memproses halaman ke-60
📄 Memproses halaman ke-61
📄 Memproses halaman ke-62
📄 Memproses halaman ke-63
📄 Memproses halaman ke-64
📄 Memproses halaman ke-65
📄 Memproses halaman ke-66
📄 Memproses halaman ke-67
📄 Memproses halaman ke-68
📄 Memproses halaman ke-69
📄 Memproses halaman ke-70
📄 Memproses halaman ke-71
📄 Memproses halaman ke-72
📄 Memproses halaman ke-73
📄 Memproses halaman ke-74
📄 Memproses halaman ke-75
📄 Memproses halaman ke-76
📄 Memproses halaman ke-77
📄 Memproses halaman ke-78
📄 Memproses halaman ke-79
📄 Memproses halaman ke-80
📄 Memproses halaman ke-81
📄 Memproses halaman ke-82
📄 Memproses halaman ke-83
📄 Memproses halaman ke-84
📄 Memproses halaman ke-85
📄 Memproses halaman ke-86
📄 Memproses halaman ke-87
📄 Memproses halaman ke-88
📄 Memproses halaman ke-89
📄 Memproses halaman ke-90
📄 Memproses halaman ke-91
📄 Memproses halaman ke-92
📄 Memproses halaman ke-93
📄 Memproses halaman ke-94
📄 Memproses halaman ke-95
📄 Memproses halaman ke-96

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Rizki Ainul Fitria,STUDI JENIS SUBSTRAT DAN HASIL TANGKAPAN RAJUN...,"Prof. Dr. Ir. Muhammad Zainuri, M. Sc","Aries Dwi Siswanto, S.T, M.T",ABSTRAK\r\n\r\nRajungan (Portunus pelagicus) m...,ABSTRACT\r\n\r\nSmall crab attaching (Portunus...
1,muhammad ghufron,ESTIMASI PERBANDINGAN KARBON DIOKSIDA DALAM BA...,"zainul hidayah, Spi. M.App.Sc","Maulinna Kusumo Wardhani, S.kel. M.Si",Muhammad Ghufron NRP. 08.03.4.11.00035. Estima...,Muhammad Ghufron NRP. 08.03.4.11.00035. Estima...
2,KIRNO MARJUKI,ANALISA KANDUNGAN GIZI DAN SENYAWA BIOAKTIF KE...,"Hafiluddin, S.Pi., M.Si","Haryo Triajie, S.Pi., M.Si","Keong Bakau (Telescopium telescopium), merupak...","Mangrove shells (Telescopium telescopium), are..."
3,MOHAMMAD FATHONI,PENYUSUNAN MODEL ALGORITMA PENDUGA KONSENTRASI...,"Firman Farid Muhsoni, S.Pi., M.Sc","Achmad Fachruddin Syah, S.Pi., M.Si",ABSTRAK\r\n\r\n\r\nDinamisnya pembangunan dan ...,ABSTRACT\r\n\r\n\r\nDynamic development and ex...
4,RENALDI SATRIA WAHYUDI,ANALISIS KANDUNGAN GIZI DAN LOGAM BERAT IKAN B...,"Hafiluddin., S.Pi., M.Si","Prof. Dr. Ir. M. Zainuri., M.Sc",Berbagai macam kegiatan yang berkaitan dengan ...,A wide range of activities related to the exis...
...,...,...,...,...,...,...
475,Nur Laili Ma'arif,Kajian Pola Arus Permukaan dan Sebaran Konsent...,"Dr. Zainul Hidayah, S.pi., M.App.Sc","Dr. Zainul Hidayah, S.pi., M.App.Sc",Pesisir Pantai Kenjeran merupakan kawasan yang...,Kenjeran Beach is an area that has a lot of to...
476,Bisri Khairil Mu'min,ANALISIS PARAMETER LINGKUNGAN SAAT TERBENTUKNY...,"Ary Giri Dwi Kartika, S.Kel.,M.Si",,ABSTRAK\n Pada tahap-tahap tertentu dalam prod...,ABSTRACT\nAt certain stages in the production ...
477,Rewandy Yehezkiel,Dinamika Perubahan Garis Pantai Di Pesisir Tel...,"Ach. Fachruddin Syah, S.Pi., M.Si., Ph.D","Ach. Fachruddin Syah, S.Pi., M.Si., Ph.D",Lingkungan pantai merupakan wilayah yang selal...,The coastal environment is an area that is alw...
478,Alief Fajar Abdillah,KARAKTERISTIK KONDISI OSEANOGRAFI DAN DISTRIBU...,"Ach. Fachruddin Syah, S.Pi., M.Si., Ph.D",,Laut Jawa (Wilayah Pengelolaan Perikanan/ WPP ...,The Java Sea (Fisheries Management Area / WPP ...
479,Terry Dwiarianto,ANALISIS PARAMETER OSEANOGRAFI UNTUK KESESUAIA...,"Achmad Fahruddin Syah, S.Pi., M.Si., Ph.D",,Pulau Gili Ketapang merupakan salah satu daera...,has an area of around 68 hectares with a popul...

### D.Prodi Manajemen SUmberdaya Perairan

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def msp():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 3):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/35/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("msp.csv", index=False)

    return df

In [ ]:
msp()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Wizarotul Labibah,Keberadaan Mikroplastik Pada Ikan Swanggi (Pri...,"Haryo Triajie, S.Pi., M.Si",,Mikroplastik merupakan sampah plastik yang men...,Microplastic is plastic waste which is degrade...
1,Nur Dina Kamelia,KAJIAN STOK RAJUNGAN (Portunus Pelagicus) DI P...,"Dr. Firman Farid Muhsoni, S.Pi., M.Sc",,Rajungan (Portunus pelagicus) merupakan komodi...,Blue Swimming Crab (Portunus pelagicus) is an ...
2,Ahmad Ibrahim,ESTIMASI STOK KARBON PADA EKOSISTEM HUTAN MANG...,"Dr. Firman Farid Muhsoni, S.Pi. M.Sc",,Meningkatnya kandungan karbon dioksida (CO2) d...,The increasing of carbon dioxide (CO2) in the ...
3,Wahidah Inayati,Analisis Beban Masuk Nutrien Terhadap Kelimpah...,"Dr. Akhmad Farid, S.Pi.,MT",,Sungai Bancaran merupakan sungai yang berada d...,Bancaran River is a river located in Bangkalan...
4,MOH. WILDANUL JANNAH,ANALISIS DAYA DUKUNG LINGKUNGAN PERAIRAN UNTUK...,"Dr. Firman Farid Muhsoni, S.Pi., M.Sc",,"Desa Saobi (Pulau Sapapan, Saobi dan Bungin Ny...","Saobi Village (Sapapan Island, Saobi and Bungi..."
5,Roihatul Jannah dan Haryo Triajie,ANALISIS KANDUNGAN TIMBAL (Pb) UDANG REBON (Ac...,"Haryo Triajie, S.Pi M.Pi",,Perairan Soccah merupakan lokasi nelayan menca...,Soccah waters are the location of fishermen lo...

### E.Prodi Magister Pengelolaan Sumber Daya Alam

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def mpsda():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 2):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/37/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("mpsda.csv", index=False)

    return df

In [ ]:
mpsda()

📄 Memproses halaman ke-1

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,ahmad syaiful umam,KARAKTERISASI DAN KOLEKSI PLASMA NUTFAH UNTUK ...,"Dr. Ir. Gita Pawana, M.Si","Dr. Ir. Hj. SIti Fatimah, M.Si",Madura merupakan salah satu wilayah pemasok ko...,Madura is one of the regions supplying horticu...
1,Siti Holifah,PENGOLAHAN LIMBAH AIR REBUSAN IKAN TERI MENJAD...,"Dr.Apri Arisandi,S.Pi.,M.Si.","Dr.Ir.H.Asfan,MP.",Ikan Teri perlu penanganan serius pasca panen ...,Anchovy needs serious handling after harvest b...
2,Mohammad Maskur,STRATEGI PENGEMBANGAN MAKANAN DAN MINUMAN KHAS...,"Dr. Akhmad Farid, S.Pi., MT","Dr. Apri Arisandi, S.Pi., M.Si",Makanan dan minuman khas merupakan ciri dari k...,Typical food and drinks are characteristic of ...

## Fakultas Ekonomi dan Bisnis

### A.Prodi Ekonomi Pembangunan

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def EP():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 119):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/6/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("EP.csv", index=False)

    return df

In [ ]:
EP()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14
📄 Memproses halaman ke-15
📄 Memproses halaman ke-16
📄 Memproses halaman ke-17
📄 Memproses halaman ke-18
📄 Memproses halaman ke-19
📄 Memproses halaman ke-20
📄 Memproses halaman ke-21
📄 Memproses halaman ke-22
📄 Memproses halaman ke-23
📄 Memproses halaman ke-24
📄 Memproses halaman ke-25
📄 Memproses halaman ke-26
📄 Memproses halaman ke-27
📄 Memproses halaman ke-28
📄 Memproses halaman ke-29
📄 Memproses halaman ke-30
📄 Memproses halaman ke-31
📄 Memproses halaman ke-32
📄 Memproses halaman ke-33
📄 Memproses halaman ke-34
📄 Memproses halaman ke-35
📄 Memproses halaman ke-36
📄 Memproses halaman ke-37
📄 Memproses halaman ke-38
📄 Memproses halaman ke-39
📄 Memproses halaman ke-40
📄 Memproses halaman ke-41
📄 Memproses halaman ke-42
📄 Memproses halaman ke-43
📄 Memproses halaman ke-44
📄 Memproses halaman ke-45
📄 Memproses halaman ke-46
📄 Memproses halaman ke-47
📄 Memproses halaman ke-48
📄 Memproses halaman ke-49
📄 Memproses halaman ke-50
📄 Memproses halaman ke-51
📄 Memproses halaman ke-52
📄 Memproses halaman ke-53
📄 Memproses halaman ke-54
📄 Memproses halaman ke-55
📄 Memproses halaman ke-56
📄 Memproses halaman ke-57
📄 Memproses halaman ke-58
📄 Memproses halaman ke-59
📄 Memproses halaman ke-60
📄 Memproses halaman ke-61
📄 Memproses halaman ke-62
📄 Memproses halaman ke-63
📄 Memproses halaman ke-64
📄 Memproses halaman ke-65
📄 Memproses halaman ke-66
📄 Memproses halaman ke-67
📄 Memproses halaman ke-68
📄 Memproses halaman ke-69
📄 Memproses halaman ke-70
📄 Memproses halaman ke-71
📄 Memproses halaman ke-72
📄 Memproses halaman ke-73
📄 Memproses halaman ke-74
📄 Memproses halaman ke-75
📄 Memproses halaman ke-76
📄 Memproses halaman ke-77
📄 Memproses halaman ke-78
📄 Memproses halaman ke-79
📄 Memproses halaman ke-80
📄 Memproses halaman ke-81
📄 Memproses halaman ke-82
📄 Memproses halaman ke-83
📄 Memproses halaman ke-84
📄 Memproses halaman ke-85
📄 Memproses halaman ke-86
📄 Memproses halaman ke-87
📄 Memproses halaman ke-88
📄 Memproses halaman ke-89
📄 Memproses halaman ke-90
📄 Memproses halaman ke-91
📄 Memproses halaman ke-92
📄 Memproses halaman ke-93
📄 Memproses halaman ke-94
📄 Memproses halaman ke-95
📄 Memproses halaman ke-96
📄 Memproses halaman ke-97
📄 Memproses halaman ke-98
📄 Memproses halaman ke-99
📄 Memproses halaman ke-100
📄 Memproses halaman ke-101
📄 Memproses halaman ke-102
📄 Memproses halaman ke-103
📄 Memproses halaman ke-104
📄 Memproses halaman ke-105
📄 Memproses halaman ke-106
📄 Memproses halaman ke-107
📄 Memproses halaman ke-108
📄 Memproses halaman ke-109
📄 Memproses halaman ke-110
📄 Memproses halaman ke-111
📄 Memproses halaman ke-112
📄 Memproses halaman ke-113
📄 Memproses halaman ke-114
📄 Memproses halaman ke-115
📄 Memproses halaman ke-116
📄 Memproses halaman ke-117
📄 Memproses halaman ke-118

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Zeni Amaliyah,ANALISIS FAKTOR – FAKTOR YANG MEMPENGARUHI PEN...,"Ris Yuwono Yudo Nugroho, SE, MSi","Bondan Satriawan, SE., MEcon.,St.",ABSTRAK\r\nStudi ini dilakukan untuk mengetahu...,ABSTRACT\r\nThis study was conducted to find o...
1,suerna,Analisis Penyerapan Tenaga Kerja Pada Industri...,"Crisanty Sutristyaningtyas Titik.S.E.,ME","Jakfar Sadik.S.E.,ME",Dalam memperluas kesempatan tenaga kerja dapat...,The expanding on labor chance to get a job can...
2,Amas Madina,Analisis MInat Migrasi di Kecamatan Arosbaya,"Andri Wijanarko, SE,ME","Widita Kurniasari, SE,ME","ABSTRAK\r\n\r\n\r\nAmas Madina, dalam peneliti...",
3,Enny Wahyuningtias,ANALISIS DETERMINAN KREDIT PELEPAS UANG UNTUK ...,"Bondan Satriawan, SE.,MEcon,St","Diah Wahyuningsih, SE.,Msi",ABSTRAK\r\n\r\n Permasalahan pedag...,
4,ACHMAD ALVIEN AFRIADI,ANALISIS FAKTOR-FAKTOR YANG MEMPENGARUHI PRODU...,"ANITA KRISTINA, SE, MSi","WIDITA KURNIASARI, SE, ME","ABSTRAK\r\nAchmad Alvien Afriadi, Analisis Fak...","ABSTRACT\r\n\r\nAchmad Alvien Afriadi, Analysi..."
...,...,...,...,...,...,...
584,Hamilah,"PENGARUH SUKU BUNGA, INFLASI, NILAI TUKAR, DAN...","Dr. Diah Wahyuningsih, S.E., M.Si",,ABSTRAK\nPenelitian ini bertujuan untuk mengan...,Abstract\nThis study aims to analyze the facto...
585,Mochammad Raharjo Priambodo,PERAN KELEMBAGAAN DALAM UPAYA PENINGKATAN PEND...,"Henny Oktavianti, S.E., M.E.",,"M Raharjo P, Peran Kelembagaan Dalam Upaya Pen...",M Raharjo P. Institutional Role In Efforts To...
586,MUHAMMAD BAKHRUL ULUM,ANALISIS STRUKTUR PASAR INDUSTRI JAJANAN TRADI...,"HENNY OKTAVIANTI.S.E.,M.E",,uhammad Bakhrul Ulum: Analisis Struktur P...,Muhammad Bakhrul Ulum: Analysis of Market...
587,MOHAMMAD FAHRUDIN,ANALISIS STRATEGI PEMBANGUNAN WISATA SENDANG B...,"Henny Oktavianti, S.E., M.E.",,Abstrak\n\nMohammad Fahrudin 150231100011. Pro...,Abstract\n\nMohammad Fahrudin 150231100011. De...
588,Sholikah Nur Aisah Putri,PENGEMBANGAN WISATA DENGAN PENDEKATAN PENGEMBA...,"Selamet Joko Utomo, S.E., M.E.",,Tujuan penelitian ini adalah untuk bagaimana p...,The purpose of this study is to develop a loca...

### Prodi Manajemen

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def manajemen():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 208):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/7/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("manajemen.csv", index=False)

    return df

In [ ]:
manajemen()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14
📄 Memproses halaman ke-15
📄 Memproses halaman ke-16
📄 Memproses halaman ke-17
📄 Memproses halaman ke-18
📄 Memproses halaman ke-19
📄 Memproses halaman ke-20
📄 Memproses halaman ke-21
📄 Memproses halaman ke-22
📄 Memproses halaman ke-23
📄 Memproses halaman ke-24
📄 Memproses halaman ke-25
📄 Memproses halaman ke-26
📄 Memproses halaman ke-27
📄 Memproses halaman ke-28
📄 Memproses halaman ke-29
📄 Memproses halaman ke-30
📄 Memproses halaman ke-31
📄 Memproses halaman ke-32
📄 Memproses halaman ke-33
📄 Memproses halaman ke-34
📄 Memproses halaman ke-35
📄 Memproses halaman ke-36
📄 Memproses halaman ke-37
📄 Memproses halaman ke-38
📄 Memproses halaman ke-39
📄 Memproses halaman ke-40
📄 Memproses halaman ke-41
📄 Memproses halaman ke-42
📄 Memproses halaman ke-43
📄 Memproses halaman ke-44
📄 Memproses halaman ke-45
📄 Memproses halaman ke-46
📄 Memproses halaman ke-47
📄 Memproses halaman ke-48
📄 Memproses halaman ke-49
📄 Memproses halaman ke-50
📄 Memproses halaman ke-51
📄 Memproses halaman ke-52
📄 Memproses halaman ke-53
📄 Memproses halaman ke-54
📄 Memproses halaman ke-55
📄 Memproses halaman ke-56
📄 Memproses halaman ke-57
📄 Memproses halaman ke-58
📄 Memproses halaman ke-59
📄 Memproses halaman ke-60
📄 Memproses halaman ke-61
📄 Memproses halaman ke-62
📄 Memproses halaman ke-63
📄 Memproses halaman ke-64
📄 Memproses halaman ke-65
📄 Memproses halaman ke-66
📄 Memproses halaman ke-67
📄 Memproses halaman ke-68
📄 Memproses halaman ke-69
📄 Memproses halaman ke-70
📄 Memproses halaman ke-71
📄 Memproses halaman ke-72
📄 Memproses halaman ke-73
📄 Memproses halaman ke-74
📄 Memproses halaman ke-75
📄 Memproses halaman ke-76
📄 Memproses halaman ke-77
📄 Memproses halaman ke-78
📄 Memproses halaman ke-79
📄 Memproses halaman ke-80
📄 Memproses halaman ke-81
📄 Memproses halaman ke-82
📄 Memproses halaman ke-83
📄 Memproses halaman ke-84
📄 Memproses halaman ke-85
📄 Memproses halaman ke-86
📄 Memproses halaman ke-87
📄 Memproses halaman ke-88
📄 Memproses halaman ke-89
📄 Memproses halaman ke-90
📄 Memproses halaman ke-91
📄 Memproses halaman ke-92
📄 Memproses halaman ke-93
📄 Memproses halaman ke-94
📄 Memproses halaman ke-95
📄 Memproses halaman ke-96
📄 Memproses halaman ke-97
📄 Memproses halaman ke-98
📄 Memproses halaman ke-99
📄 Memproses halaman ke-100
📄 Memproses halaman ke-101
📄 Memproses halaman ke-102
📄 Memproses halaman ke-103
📄 Memproses halaman ke-104
📄 Memproses halaman ke-105
📄 Memproses halaman ke-106
📄 Memproses halaman ke-107
📄 Memproses halaman ke-108
📄 Memproses halaman ke-109
📄 Memproses halaman ke-110
📄 Memproses halaman ke-111
📄 Memproses halaman ke-112
📄 Memproses halaman ke-113
📄 Memproses halaman ke-114
📄 Memproses halaman ke-115
📄 Memproses halaman ke-116
📄 Memproses halaman ke-117
📄 Memproses halaman ke-118
📄 Memproses halaman ke-119
📄 Memproses halaman ke-120
📄 Memproses halaman ke-121
📄 Memproses halaman ke-122
📄 Memproses halaman ke-123
📄 Memproses halaman ke-124
📄 Memproses halaman ke-125
📄 Memproses halaman ke-126
📄 Memproses halaman ke-127
📄 Memproses halaman ke-128
📄 Memproses halaman ke-129
📄 Memproses halaman ke-130
📄 Memproses halaman ke-131
📄 Memproses halaman ke-132
📄 Memproses halaman ke-133
📄 Memproses halaman ke-134
📄 Memproses halaman ke-135
📄 Memproses halaman ke-136
📄 Memproses halaman ke-137
📄 Memproses halaman ke-138
📄 Memproses halaman ke-139
📄 Memproses halaman ke-140
📄 Memproses halaman ke-141
📄 Memproses halaman ke-142
📄 Memproses halaman ke-143
📄 Memproses halaman ke-144
📄 Memproses halaman ke-145
📄 Memproses halaman ke-146
📄 Memproses halaman ke-147
📄 Memproses halaman ke-148
📄 Memproses halaman ke-149
📄 Memproses halaman ke-150
📄 Memproses halaman ke-151
📄 Memproses halaman ke-152
📄 Memproses halaman ke-153
📄 Memproses halaman ke-154
📄 Memproses halaman ke-155
📄 Memproses halaman ke-156
📄 Memproses halaman ke-157
📄 Memproses halaman ke-158
📄 Memproses halaman ke-159
📄 Memproses halaman ke-160
📄 Memproses halaman ke-161
📄 Memproses halaman ke-162
📄 Memproses halaman ke-163
📄 Memproses halaman ke-164
📄 Memproses halaman ke-165
📄 Memproses halaman ke-166
📄 Memproses halaman ke-167
📄 Memproses halaman ke-168
📄 Memproses halaman ke-169
📄 Memproses halaman ke-170
📄 Memproses halaman ke-171
📄 Memproses halaman ke-172
📄 Memproses halaman ke-173
📄 Memproses halaman ke-174
📄 Memproses halaman ke-175
📄 Memproses halaman ke-176
📄 Memproses halaman ke-177
📄 Memproses halaman ke-178
📄 Memproses halaman ke-179
📄 Memproses halaman ke-180
📄 Memproses halaman ke-181
📄 Memproses halaman ke-182
📄 Memproses halaman ke-183
📄 Memproses halaman ke-184
📄 Memproses halaman ke-185
📄 Memproses halaman ke-186
📄 Memproses halaman ke-187
📄 Memproses halaman ke-188
📄 Memproses halaman ke-189
📄 Memproses halaman ke-190
📄 Memproses halaman ke-191
📄 Memproses halaman ke-192
📄 Memproses halaman ke-193
📄 Memproses halaman ke-194
📄 Memproses halaman ke-195
📄 Memproses halaman ke-196
📄 Memproses halaman ke-197
📄 Memproses halaman ke-198
📄 Memproses halaman ke-199
📄 Memproses halaman ke-200
📄 Memproses halaman ke-201
📄 Memproses halaman ke-202
📄 Memproses halaman ke-203
📄 Memproses halaman ke-204
📄 Memproses halaman ke-205
📄 Memproses halaman ke-206
📄 Memproses halaman ke-207

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,SATIYAH,PENGARUH FAKTOR-FAKTOR PELATIHAN DAN PENGEMBAN...,"Dra. Hj. S. Anugrahini Irawati, MM","Helmi Buyung Aulia,S,ST.SE,M.MT","ABSTRAK\r\nSatiyah, Pengaruh Faktor-faktor Pel...",ABSTRACT\r\n\r\nIn an effort to increase labor...
1,Faishal,ANALISIS PERSEPSI BRAND ASSOCIATION MENURUT PE...,Nurita Andriani,Yustina Chrismardani,Tujuan penelitian ini adalah untuk mengetahui ...,This study wanted to know the brand associatio...
2,Wahyu Kurniawan,PENGARUH GAYA KEPEMIMPINAN DEMOKRATIK TERHADAP...,"Dr. Dra. Hj. Iriani Ismail, MM","Dra. Hj. S. Anugrahini Irawati, MM",,
3,Muhammad Zakaria Utomo,Pengukuran Website Quality Pada Situs Sistem A...,"Dr. Ir. Nurita Andriani, MM","Nirma Kurriwati, SP, M.Si",Aplikasi nyata pemanfaatan teknologi informasi...,Academic portal system in University of Trunoj...
4,Hendri Wahyudi Prayitno,PENGARUH KEPEMIMPINAN DAN KOMPENSASI TERHADAP ...,"Dra. Hj. S Anugrahini Irawati, MM","Helmi Buyung Aulia,S,ST,SE,.MT",Abstrak\r\nPenelitian ini menggunakan metode k...,Abstract\r\nThis research use quantitative met...
...,...,...,...,...,...,...
1026,Husnul Hotimah,Analisis Cost Volume Profit Untuk Menentukan T...,"Hj. Evaliati Amaniyah, S.E., M.S.M.",,ABSTRAK\nPenelitian ini bertujuan untuk menget...,ABSTRACT\nThis study aims to determine the cal...
1027,Uswatun Hasanah,Pengaruh Pelatihan Dan Kompensasi Terhadap Pro...,"Dr. Raden Mas Mochammad Wispandono S.E ., MS",,"ABSTRAK\nUswatun Hasanah, 160211100291, Pengar...","ABSTRACT\nUswatun Hasanah, 160211100291, The E..."
1028,ACH FATHONI,PERAN SERVICE PERFORMANCE DAN CLIMATE ORGANIZA...,"YUDHI PRASETYA MADA, S.E., M.M.",,ABSTRAK\nTujuan dari penelitian ini adalah unt...,ABSTRACK\n The purpose of this study...
1029,INTAN YULLIA NINGSIH,BAURAN PROMOSI PADA DEALER YAMAHA TRETAN MOTOR...,"DR. MOHAMMAD ARIEF, S.E., M.M.",,ABSTRAK\nPenelitian ini bertujuan: (1) Untuk m...,ABSTRACK\nThis study aims: (1) To find out whe...
1030,Widha Deby Andrea,Peran Teor Motivasi Herzberg Sebagai Mediator ...,"Mochammad Isa Anshori, S.E., M.Si.",,Penelitian ini bertujuan untuk dapat mengetahu...,This study aims to find out about the effect o...

### Akutansi

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def akutansi():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 178):
        # print(f"📄 Memproses halaman ke-{i}")  ← Dihilangkan atau dikomentari
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/8/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("akutansi.csv", index=False)

    return df

In [ ]:
akutansi()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Nida Qolbi,PENTINGNYA KOMPETENSI PEJABAT PENGADAAN BARANG...,"Mohammad Djasuli,SE., M.Si., QIA","Gita Arasy Harwida,SE.,Ak.,M.Tax,QIA",Abstrak : Pentingnya Kompetensi Pejabat Pengad...,"ABSTRAK\r\nQolbi, Nida 2012 “ The Importance C..."
1,Rr. ALVIN SHARAS,ANALISIS PERLAKUAN AKUNTANSI TABUNGAN DENGAN S...,"Prof. Dr. H. M. Nizarul Alim, SE., M.Si., Ak","Rita Yuliana, SE,M.S.A., Ak",ABSTRAK\r\n\r\nWadiah telah berkembang dalam d...,ABSTRACT\r\n\r\nWadiah has grown in world syar...
2,MOH. MUKROM,PERSEPSI MAHASISWA TENTANG MODEL PEMBELAJARAN ...,"RITA YULIANA, SE., MSA., Ak","JUNAIDI, SE., MSi., Ak",ABSTRAK\r\n\r\nKeberadaan beasiswa di Fakultas...,ABSTRACT\r\n\r\nExistence scholarship at the e...
3,KARTIKA RUSNINDITA,ANALISIS FUNGSI LAKIP SEBAGAI PENGUKURAN KINER...,"JUNAIDI SE,M.Si.,Ak","NURHAYATI SE,MSA.,Ak",ABSTRAK\r\n\r\nPenelitian ini bertujuan untuk ...,ABSTRACT\r\n\r\nThis study is aimed to know ho...
4,DEWI AGUS NORFITRIAH,PENGARUH FAKTOR-FAKTOR TINGKAT KESULITAN DALAM...,"ANIS WULANDARI, SE., M.SA., Ak","NURUL KOMPYURINI, SE., Ak., MAk","Agus Norfitriah, Dewi. 2012. Pengaruh Faktor-F...","Agus Norfitriah, Dewi. 2012. Influence of Fact..."
...,...,...,...,...,...,...
878,Suci Indahsari,PENGELOLAAN DAN PEMANFAATAN DANA KAPITASI (St...,"Citra Nurhayati, S.E.,MA.,Ak.,CA.",,ABSTRAK\nPengelolaan dan pemanfaatan dana kapi...,ABSTRACT\n Management and utilization of capit...
879,Nafisatun Nufus,ANALISIS FAKTOR FAKTOR YANG MEMPENGARUHI KUALI...,"Dr. Siti Musyarofah, S.E., M.Si., Ak., CA",,ABSTRAK\nPenelitian ini bertujuan untuk yang 1...,ABSTRACT\nThis study aims to 1.) Analyze the i...
880,Anis Nurlaeli,ANALISIS PENGARUH SISTEM PENGENDALIAN INTERNAL...,"Dr. Siti Musyarofah, S.E., M.Si., AK.,CA",,ABSTRAK\n \nPenelitian ini bertujuan untuk men...,ABSTRACT\n\n The purpose of this research are ...
881,Ernia Juniati,"Pengaruh Kualitas Sumber Daya Manusia, Pemaham...","Citra Nurhayati, S.E., M.A., Ak., CA",,Penelitian ini bertujuan untuk mengetahui peng...,This study aims to determine the effect of the...
882,Eka Septia Putri,"PENGARUH LAPORAN ARUS KAS, LABA BERSIH DAN SIZ...","Alexander Anggono, S.E. , M.Si . , PhD",,"ABSTRAK\n \nEka Septia Putri, Pengaruh Laporan...","ABSTRACT \n \nEka Septia Putri, The Effect of ..."

### D3 Akutansi

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def d3akutansi():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 32):
        # print(f"📄 Memproses halaman ke-{i}")  ← Dihilangkan atau dikomentari
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/21/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("d3akutansi.csv", index=False)

    return df

In [ ]:
d3akutansi()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,novarika yunia kusuma wardani,Sistem Informasi Akuntansi Upah kepada Pegawai...,"Nurul Kompyurini, S.E., M.Ak., Ak","Anita Carolina, S.E., MbusAdv., Ak., QIA, CA.",PT PELINDO III (Persero) cabang Tanjung Perak ...,PT PELINDO III (Persero) Tanjung Perak Surabay...
1,SITI LATIFATUL KAMALIA,"EVALUASI PEMOTONGAN, PENYETORAN DAN PELAPORAN ...","Yudhanta Sambharakreshna, S.E., M.Si., Ak","Rindah Febriana Suryawati, S.E., M.Acc., Ak","Evaluasi pemotongan, penyetoran dan pelaporan ...","Evaluation of cutting, depositing and reportin..."
2,Priya Agung Budi Wicaksono,analisis pengendalian internal terhadap peneri...,"Citra Nurhayati, S. E., MA., Ak","Anita Carolina. S. E., MbusAdv., Ak., QIA, CA","ABSTRAK\r\n\r\nPriya Agung Budi Wicaksono, Ana...","ABSTRACT\r\n\r\nPriya Agung Budi Wicaksono, An..."
3,RB ALIF REZA K,Peranan Pendapatan Asli Daerah dalam Menunjang...,"Nurul Herawati, S.E., M.Si., Ak","Rahmat Zuhdi, S.E., M.SA., CA., Ak., QIA",Pemerintah daerah sebagai induk sistem pemerin...,Local government as the main system of governm...
4,Choirur Rozikin,"ANALISIS PROSES PEMOTONGAN, PENYETORAN, DAN PE...","Nurul Kompyurini, S.E., M.Ak., Ak","Erfan Muhammad, S.E., M.Ak., CPA","Abstrak\r\n\r\nChoirur Rozikin, Analisis Prose...","Abstract\r\n\r\nChoirur Rozikin, Analysis of D..."
...,...,...,...,...,...,...
146,Vira Damara Putri Suganda,Evaluasi Sistem Penerimaan Kas Pada Perusahaan...,"Yuni Rimawati, S.E., M.S.Ak., Ak., CA.",,"Vira Damara Putri Suganda, Evaluasi Sistem Pen...","Vira Damara Putri Suganda, Evaluation of Cash ..."
147,FAIRUSUL UMAM,EVALUASI PENERAPAN PEMOTONGAN DAN PENYETORAN ...,"Muhammad Asim Asy’ari, SE., M. Ak",,"Fairusul Umam, Evaluasi Penerapan Pemotongan, ...","Fairusul Umam, Evaluation Application Cuts, Ta..."
148,SAIPUL BAHRI,ANALISIS SISTEM DAN PROSEDUR IZIN MENDIRKAN BA...,"Achdiar Redy Setiawan, S.E., MSA., Ak., CA",,SISTEM DAN PROSEDUR PEROLEHAN IZIN MENDIRIKAN ...,SYSTEM AND PROCEDURES FOR PERMISSION OF LICENS...
149,NURUL AULIA NINGSIH,PENCATATAN LAPORAN KEUANGAN BERBASIS STANDAR A...,"FARIYANA KUSUMAWATI, S.E., M.Sc.",,PENCATATAN LAPORAN KEUANGAN BERBASIS STANDAR A...,PENCATATAN LAPORAN KEUANGAN BERBASIS STANDAR A...
150,IMRON ROSYADI,EVALUASI KINERJA ORGANISASI INSPEKTORAT PEMERI...,"Adi Darmawan Ervanto, S.E., MA., Ak., CA",,Penelitian ini berjudul evaluasi kinerja organ...,The study titles is the evaluation of the orga...

Magister Manajemen

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def magistermanajemen():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 15):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/22/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("magistermanajemen.csv", index=False)

    return df

In [ ]:
magistermanajemen()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,"Jaka Ardiansyah, S.E","PENGARUH INFLASI, NILAI TUKAR RUPIAH DAN TINGK...","Dr. Chairul Anam, Drs.Ec., M.Kes","Dr. H. Pribanus Wantara, Drs., MM",Penelitian ini bertujuan untuk mengetahui peng...,This Research aimed to analyzed the effect of ...
1,"Dian Yunita Syaiful, SE","Pengaruh Current Ratio, Debt To Equity Ratio, ...","Dr. Chairul Anam, Drs. Ec., M.Kes","Dr. Raden M. Mochammad Wispandono, S.E., MS",Return atau hasil investasi merupakan tujuan u...,Return or the return on investment is a prime ...
2,"VERY ANDRIANINGSIH,SE","Pengaruh Profitabilitas, Likuiditas, dan Stru...","Dr. Drs. Chairul Anam, M. Kes","Dr. Muhammad Alkirom Wildan, SE. MSi",Tujuan penelitian ini adalah untuk mengetahui ...,Research approach used in this research is the...
3,Mochammad Mangkus Efendi,PENGARUH KUALITAS PELAYANAN TERHADAP LOYALITAS...,"Dr.H. Pribanus Wantara., MM","Dr. H. Muh. Syarif. Drs. Ec.,M.Si",Penelitian ini ingin mensinergikan tiga variab...,Abstract\r\n\r\n\r\nThis study wants to synerg...
4,AHMAD MUSTAIN SALEH,STRATEGI REKRUTMEN DAN SELEKSI \r\nUNTUK MENIN...,"Dr. Muhammad Alkirom Wildan, SE., M.Si","Dr. Hj. Iriani Ismail, Dra., MM","ABSTRAK\r\nMUSTAIN, A. 2015. STRATEGI REKRUTME...","MUSTAIN, A. 2015. HIRING AND SELECTION TO IM..."
...,...,...,...,...,...,...
65,Nanto Purnomo,Analisis Kualitas Website Dan Reputasi Vendor ...,"Dr. Mohammad Arief, SE.,MM","Dr. H. Pribanus Wantara, Drs., M.M",Penelitian ini bertujuan untuk menganalisis ke...,This study aims to analyze online purchasing d...
66,FITRIYAH S. Fil.I,STRATEGI PENGEMBANGAN SUMBER DAYA MANUSIA DEN...,"Dr. Hj. Iriani Ismail, Dra., M.M","Dr. H. Muh. Syarif, Drs. E.c., M.Si",Penelitian ini merupakan penelitian deskriptif...,The population is Civil Servants (PNS) in the ...
67,"YOLA PRATAMA, ST.",ANALISIS QUALITY OF WORK LIFE TERHADAP ORGANIZ...,"Dr. Muhammad Alkirom Wildan, SE., MSi.","Dr. Ir. Nurita Andriani, M.M.",Penelitian ini bertujuan untuk mengetahui sebe...,The aims of this study are to determine the ef...
68,Kristianto,PENGARUH KOMUNIKASI DAN KONFLIK INTERPERSONAL ...,"Dr. RM. Moch. Wispandono, SE, MS.","Dr. H. Pribanus Wantara, Drs., MM ..",ABSTRAK\n\nKristianto. Pengaruh Komunikasi dan...,ABSTRACT\n\nResearcher takes title in this res...
69,Zaini,ZAINI. 2019. Kompetensi Pengelola dalam Pengel...,"Dr. Muhammad Alkirom Wildan. S.E., M.Si","Dr. A Yahya Surya Winata. S.E., M. Si",,ZAINI. 2019. Management Competence in the Mana...

Magister Akutansi

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def magisterakutansi():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 20):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/25/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("magisterakutansi.csv", index=False)

    return df

In [ ]:
magisterakutansi()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,RILLA IZZATUL HAQQI,LIKUIDITAS DAN PROFITABILITAS DIGUNAKAN UNTUK ...,"Prof. Dr. H. Moh. Nizarul A, SE., M.Si., Ak","Dr. Tarjo, SE., M.SI., CFE",Penelitian ini bertujuan untuk mengetahui rasi...,This study aims to determine the financial rat...
1,ANNISA MAULA HIKMAH,PERSEPSI PEJABAT PUBLIK TERHADAP GRATIFIKASI P...,"Prof. Dr. H. M. Nizarul Alim, SE, M.Si., Ak","Dr. Bambang Haryadi, SE., M.Si., Ak., CPA",UU No 20 Tahun 2001 menyebutkan bahwa gartif...,Law No. 20 of 2001 stipulates that gartifikasi...
2,Yahya Rochman,"PENGARUH KOMPETENSI, TEKANAN KETAATAN, PENGALA...","Dr. Bambang Haryadi, SE.,M.Si.,Ak.,CA","Dr. Prasetyono, SE.,M.Si.,Ak",Tujuan dari penelitian ini adalah untuk mengan...,The purpose of this study was to analyze the e...
3,HARIRI,ANALISIS KECURANGAN LAPORAN KEUANGAN PERUSAHAA...,"Prof. Dr. M. Nizarul Alim, SE., M.Si., Ak., CA","Dr. Tarjo, SE., M.Si., CFE",Abstrak-Penelitian ini bertujuan untuk mendete...,Abstract-This research aims to detect fraudule...
4,Imam Agus Faisol,PENGARUH PENERAPAN E-PROCUREMENT TERHADAP PENC...,"Dr. Tarjo, SE., M.Si., CFE","Dr. Siti Musyarofah, S.E., M.Si., Ak., CA","Imam Agus Faisol, Analisis Penerapan e-procure...","Imam Agus Faisol, Analyze Impact of Implementa..."
...,...,...,...,...,...,...
88,SUGIYANTO,"PENGARUH BEBAN KERJA, SKEPTISME PROFESIONAL, I...","Dr. Bambang Haryadi, S.E., M.Si, Ak, CA","Alexander Anggono, SE., M.Si., Ph.D",Tujuan penelitian ini yaitu untuk mendapatkan ...,The purpose of this study is to obtain empiric...
89,Elita Aprilianty,"SIKAP, NORMA SUBJEKTIF, PERSEPSI KONTROL PERIL...","Dr. Bambang Haryadi, S.E., M.Si., Ak., CA., CFrA","Dr. Prasetyono, SE., M.Si., Ak., CFrA",Tujuan dari penelitian ini adalah untuk menget...,The purpose of this study was to find out how ...
90,Rudy Mikiyanto Kusumo,MENDETEKSI INDIKASI FRAUD PADA LAPORAN KEUANGA...,"Dr. Tarjo, S.E., M.Si, CFE","Dr. Bambang Haryadi, S.E., M.Si., Ak., Ak",Umumnya keterjadian kebangkrutan beriringan de...,Generally bankruptcy coincides with fraud. As ...
91,Nur Endah Rochmawati,IMPLEMENTASI GOOD CORPORATE GOVERNANCE SEBAGAI...,"Dr. Tarjo, SE., M.Si., CFE","Dr. Siti Musyarofah, SE., M.Si., Ak. CA",Perkembangan kondisi perbankan di Indonesia te...,The development of banking conditions in Indon...
92,Suyono,PENENTUAN FEE AUDIT PADA KANTOR AKUNTAN PUBLIK,"Dr. Bambang Haryadi, SE., M.Si., Ak. CA","Dr. Siti Musyarofah, SE., M.Si., Ak. CA",Penelitian ini dilakukan untuk mengetahui pene...,This research was conducted to determine the d...

D3 Enterpreneurship

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def d3enterpreneurship():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 16):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/26/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("d3enterpreneurship.csv", index=False)

    return df

In [ ]:
d3enterpreneurship()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Ramdhani Febriyansyah,LAPORAN KERJA USAHA DI\nPERUSAHAAN “GOOD.DEAR”,"Drs. Ec. Bambang Sudarsono, M.M",,"ABSTRAK\n Ramdhani Febriyansyah, 2016. Laporan...","ABSTRACT\nRamdhani Febriyansyah, 2016. Busines..."
1,SITI FARIDATUL HASANAH,PENINGKATAN KUALITAS PRODUK PADA UD. UBER JAYA...,"Saniman, SE., M.PSDM.",,"ABSTRAK\n Siti Faridatul Hasanah, “Peningkatan...","ABSTRACT\nSiti Faridatul Hasanah, ""Improved qu..."
2,ANIK RIYANI,ANALISIS KUALITAS TENAGA KERJA PEMASARAN \nDI ...,Drs. Ec. Mudji Kuswinarno,,"ABSTRAK\n\n Anik Riyani, “Analisis Kualitas Te...","ABSTRACT\n\n Anik Riyani, “Analysis of Quality..."
3,PRADINA EKA ANUGRAHENY,LAPORAN KERJA USAHA \nDI \nPABRIK TAHU UD. SUM...,Drs. Ec. Bambang Sudarsono. MM.,,ABSTRAK\nPradina Eka Anugraheny (130271100002)...,ABSTRACT\nPradina Eka Anugraheny (130271100002...
4,DWI LAILI SYAFAAH,STRATEGI PEMASARAN PADA PERUSAHAAN\nCV.PETIS M...,"Drs.Ec. Mudji Kuswinarno, M.Si",,"ABSTRAK\nDwi laili Syafaah, Strategi Pemasaran...","ABSTRACT\n\n Dwi Laili Syafaah, Marketing Stra..."
...,...,...,...,...,...,...
67,ERNI YUSNITA,Analisis Peranan Modal Kerja Terhadap Peningka...,"R. Gatot Heru Pranjoto, SE., MM",,ABSTRAK\n\nModal kerja menjadi faktor yang san...,ABSTRACT\n\nWorking capital is a very importan...
68,Desy Syska Nur Aisyah,EFEKTIFITAS SISTEM MONITORING PADA RUMAH MAKAN...,"Faidal, SE., MM",,ABSTRAK\n“Analisis Kepuasan Konsumen Rumah Mak...,"ABSTRACK ""Analysis of Satisfaction of Tera Bul..."
69,Nuruz Zakiyah,PROSES REKRUITMEN KARYAWAN DI PT. MADURA CONSU...,"Saniman., SE.M.PSDM",,"ABSTRAK\n\nNuruz Zakiyah, 160271100013. Proses...","ABSTRACT\n\nNuruz Zakiyah, 160271100013. Recru..."
70,Karina Nurul Komariah,PERANAN PENILAIAN PRESTASI KERJA DALAM MENINGK...,"R. Gatot Heru Pranjoto, SE., MM",,Penelitian ini dilatarbelakangi dari adanya pe...,The study was backed by the presence of the in...
71,RIZKY ALANDO ARIF,KOMUIKASI PEMASARAN DALAM MENARIK KLIEN GUNA M...,"DARUL ISLAM, SE., MM",,Televisi adalah media masa yang sering digunak...,Television is mass media that is often used by...

Magister Ilmu Ekonomi

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def magisterekonomi():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 3):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/36/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("magisterekonomi.csv", index=False)

    return df

In [ ]:
magisterekonomi()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,SUMARTO,Analisis Ketaatan Maqashid Syariah\nterhadap P...,"Dr. Sutikno S.E., M.E","Dr. Anita Kristina S.E., M.Si",Penelitian ini bertujuan untuk menganalisis ba...,This study aims to analyze how the effects of ...
1,MUSOFFAN,Analisis Daya Dukung Dermaga Branta Pesisir S...,"Dr. Kurniyati Indahsari, M.Si","Dr. Agus Romadhon, SP. M.Si",Dermaga Branta di Desa Branta Pesisir Kecamat...,Branta Port in Branta Pesisir Tlanakan Pamekas...
2,Moh. Syarif,ANALISIS PENENTUAN BESARAN DAN PENGELOLAAN DAN...,Eni Sri Rahayu Ningsih,Mohtar Rasyid,Dana Desa adalah dana yang bersumber dari Angg...,The Village Fund is a funding that sourced fro...
3,ULY MABRUROH HALIDA,PERBANDINGAN PAJAK DAN RETRIBUSI DENGAN ZAKAT ...,"Dr. SUTIKNO, S.E., M.E.","Dr. KURNIYATI INDAHSARI, MSi",Penelitian ini bertujuan untuk mengetahui perb...,This study aims to determine the difference be...
4,Sri Rohyatiningsih,PENGARUH TUNJANGAN KINERJA TERHADAP PRODUKTIVI...,"Dr. Mohtar Rasyid, S.E., M.Sc","Dr. Anita Kristina, S.E., M.Si",Seiring dengan adanya tunjangan kinerja bagi p...,Along with the performance allowance for emplo...
5,INDHIARSIH SALINDRI,Pola Mobilitas Komutasi Bagi Pegawai Kontrak d...,"Dr. Anita Kristina, S.E., M.Si.","Dr. Mohtar Rasyid, S.E., M.Sc.",Penelitian ini bertujuan untuk mengungkap feno...,This study aims to reveal the phenomenon of co...
6,"Lisa Sri rahmatullah, S. Sos. I",Dampak Sosial Ekonomi Pariwisata Religi Makam ...,"Dr. Diah Wahyuningsih, S.E., M.Si.","Dr. Eni Sri Rahayuningsih, S.E., M.E.",Penelitian ini bertujuan untuk mengetahui baga...,The purpose of this study is to analyze the so...
7,Indah Ainun Nikmah,Peranan Zakat Produktif Dalam Meningkatkan Eko...,"Dr. Kurniyati Indahsari, M.Si","Dr. Abdur Rahman, S.Ag. MEI",Peranan Zakat Produktif dalam Meningkatkan Eko...,The Role of Productive Zakat in Improving Must...

Doktor Ilmu Manajemen

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def doktormanajemen():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 2):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/41/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("doktormanajemen.csv", index=False)

    return df

In [ ]:
doktormanajemen()

Empty DataFrame
Columns: [penulis, judul, pembimbing_pertama, pembimbing_kedua, abstrak_indo, abstrak_inggris]
Index: []

## Fakultas Teknik

### Teknik Industri

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def TI():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 144):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/9/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("TI.csv", index=False)

    return df

In [ ]:
TI()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Siliwangi Fitra Rachmawanto S.T.,OPTIMASI PEMILIHAN PORTOFOLIO SAHAM PERUSAHAAN...,"Heri Awalul Ilhamsah S.T., M.T.","Retno Indriartiningtias S.T., M.T.",Portofolio adalah sekumpulan saham yang dimili...,Portofolio is a collection of stock owned by i...
1,AHMAD MAS'UD,PERANCANGAN TATA LETAK FASILITAS LANTAI PRODUK...,"SABARUDIN AKHMAD, S.T., M.T.","SUGENG PURWOKO, S.T., M.T.",PT. ABC merupakan perusahaan yang bergerak dib...,PT. ABC is a company engaged in the manufactur...
2,Yulianto Fauzanta,PERUMUSAN STRATEGI BISNIS UD. BUDI JAYA BANGKA...,"Fitri Agustina, S.T., M.T","Retno Indriartiningtias, S.T., M.T",Bangkalan merupakan salah satu kabupaten yang ...,Bangkalan is one of the districts that have th...
3,M Mundir Muhlisin,USULAN PERBAIKAN UTILITAS RESOURCES PADA LANTA...,Mu'alim ST MT,Sugeng Purwoko ST MT,Simulasi adalah duplikasi atau abstraksi dari ...,Simulation is a duplication or abstraction of ...
4,Muhibbin,Peningkatan Kepuasan Masyarakat Terhadap Pelay...,Rahmad Hidayat,Retno Indriartiningtias,Kepuasan adalah tingkat perasaan seseorang ter...,Satisfaction is feeling level of someone to se...
...,...,...,...,...,...,...
706,YOLANDA ABIGAIL LAPIAN,USULAN PERBAIKAN UPAYA MINIMASI REJECT PART BO...,"Prof. Dr. Rachmad Hidayat, M.T.,IPU, Asean Eng","Imron Kuswandi S.T., M.T",Kualitas dan pengendalian kualitas memiliki pe...,Quality and quality control have an important ...
707,Nisfu Laylatus Sabihis,PERENCANAAN KEBIJAKAN PENGENDALIAN PERSEDIAAN ...,"Sugeng Purwoko, S.T., M.T","Mu'alim, S.T., M.T",PT. Apie Indo Karunia merupakan suatu perusaha...,PT. Apie Indo Karunia is a company in the man...
708,Muhammad Asri Wahyu Dianto,PENGEMBANGAN DAN KARAKTERISASI HASIL ASSESSMEN...,"Dr.Sabarudin Akhmad, S.T., M.T., IPM. Asean Eng","Anis Arendra S.T,. M.Eng",MSDs atau Musculoskeletal Disorders adalah gan...,MSDs or Musculoskeletal Disorders are injuries...
709,MUNIF SAYID ANWAS PRABOWO,Evaluasi Tingkat Kelelahan Kerja Perawat Ruang...,"Dr. Weny Findiastuti, S.T.,M.T","Rullie Annisa, S.T.,M.T",Rumah sakit merupakan salah satu instansi di b...,The hospital is one of the institutions in the...
710,Lilis Kurnia Ikamawati,PENENTUAN TINGKAT PRIORITAS PERBAIKAN MODE KEG...,"Dr. Kukuh Winarso, S.Si., M.T, IPM. Asean Eng","Issa Dyah Utami, S.T., M.T.",Penelitian ini berlokasikan di PT Semen Indone...,This research is located at PT Semen Indonesia...

### Teknik Informatika

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def TIF():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 173):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/10/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("TIF.csv", index=False)

    return df

In [ ]:
TIF()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,A.Ubaidillah S.Kom,PERANCANGAN DAN IMPLEMENTASI SISTEM DATABASE \...,Budi Setyono M.T,Hermawan S.T,Sistem informasi akademik (SIAKAD) merupaka...,Academic information systems (SIAKAD) is an in...
1,"M. Basith Ardianto,",APLIKASI KONTROL DAN MONITORING JARINGAN KOMPU...,"Drs. Budi Soesilo, MT","Koko Joni, ST",Berjalannya koneksi jaringan komputer dengan l...,-
2,"Akhmad Suyandi, S.Kom",RANCANG BANGUN APLIKASI PROXY SERVER UNTUK\r\n...,"Drs. Budi Soesilo, M.T","Hermawan, ST, MT",Web server adalah sebuah perangkat lunak serve...,Web server is a server software functioning to...
3,Heri Supriyanto,SISTEM PENDUKUNG KEPUTUSAN OPTIMASI PENJADWALA...,"Mulaab, S.Si., M.Kom","Firli Irhamni, ST., M.Kom",Penjadwalan kuliah di Perguruan Tinggi me...,Scheduling courses in universities is a ...
4,Septian Rahman Hakim,SISTEM AUGMENTED REALITY ANIMASI BENDA BERGERA...,"Arik Kurniawati, S.Kom., M.T.","Haryanto, S.T., M.T.",Seiring perkembangan teknologi yang ada diduni...,As the development of technology existing in t...
...,...,...,...,...,...,...
853,Rachmad Agung Pambudi,PENERAPAN ALGORITMA LONG-SHORT TERM MEMORY UNT...,"Eka Mala Sari Rochman, S.Kom., M.Kom","Sri Herawati, S.Kom., M.Kom",Investasi saham selama ini memiliki resiko ker...,Investment in shares so far has a very large r...
854,Nadila Hidayanti,SISTEM PENCARIAN TEKS AL-QURAN TERJEMAHAN BERB...,"Achmad Jauhari, S.T., M.Kom","Ika Oktavia Suzanti, S.Kom., M.Cs",Information Retrieval (IR) merupakan pengambil...,Information Retrieval (IR) is retrieval of inf...
855,Afni Sakinah,KLASIFIKASI KOMPLEKSITAS VISUAL CITRA SAMPAH M...,"Dr. Indah Agustien Siradjuddin, S.Kom., M.Kom.","Moch. Kautsar Sophan, S.Kom., M.MT.",Klasifikasi citra merupakan proses pengelompok...,Image classification is a process of grouping ...
856,Friska Fatmawatiningrum,IDENTIFIKASI BINER ATRIBUT PEJALAN KAKI MENGGU...,"Dr. Indah Agustien Siradjuddin, S.Kom., M.Kom.","Prof. Dr. Arief Muntasa, S.Si., M.MT.",Identifikasi atribut pejalan kaki merupakan sa...,The identification of pedestrian attributes is...
857,Dian Wibowo,DETEKSI OBJEK MANUSIA BERBASIS ONE STAGE DETEC...,"Dr. Indah Agustien Siradjuddin, S.Kom., M.Kom.","Moch. Kautsar Sophan, S.Kom., M.MT.",Topik deteksi objek telah menarik perhatian ya...,The topic of object detection has attracted gr...

### Manajemen Informatika

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def manajemeninformatika():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 57):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/11/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("manajemeninformatika.csv", index=False)

    return df

In [ ]:
manajemeninformatika()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Elky Lilik Misdayani,SISTEM INFORMASI PERUSAHAAN OTOBUS SUMBER KENC...,"Fitri Damayanti,S.Kom,M.Kom",,Sistem informasi pengolahan data yang dibutuhk...,Data processing information systems needed by ...
1,lu'luul maknun,SISTEM INFORMASI GEOGRAFIS PEMETAAN POTENSI OB...,"Aeri Rahmad,S.T,M.T",-,Abstrak\r\nPerkembangan teknologi di berbagai ...,Abstract\r\nData processing systems required b...
2,Megawati Bukhori Putri,SISTEM INFORMASI PSIKOTES BERBASIS DEKSTOP,"Yeni Kustianingsih, S.Kom, M.Kom",-,Abstrak\r\nPerkembangan teknologi di berbagai ...,Abstract\r\nTechnological developments in vari...
3,Andika Syarifuddin Parmana Putra,Perancangan Dan Pembuatan Sistem Informasi Man...,"Sri Herawati,S.Kom","Sri Herawati,S.Kom",Abstrak\r\n\r\nSistem Informasi Manajemen Data...,Abstract\r\n\r\nData Management Information Sy...
4,Deka Pranaristanto,SISTEM INFORMASI PEMESANAN RUMAH BERBASIS WEB ...,"Budi Dwi Satoto S.T, M.Kom","Budi Dwi Satoto S.T, M.Kom",Sistem pemesanan atau profil tentang PT. PROPI...,Ordering system or the profile of PT. MAIN WIR...
...,...,...,...,...,...,...
275,MAKBUL ZAKARIYA,APLIKASI PEMESANAN SIRKUIT LINTASAN BALAP BERB...,"FITRI DAMAYANTI, S.KOM., M.KOM",,Masyarakat harus datang terlebih dahulu untuk ...,The public must come first to order the race t...
276,Tri Nanda Irawan,SISTEM MONITORING PENILAIAN KINERJA PEGAWAI\nP...,"Novi Prastiti, S.Kom., M.Kom",,Pengertian Penilaian kinerja pegawai adalah su...,Understanding Employee appraisal is a structur...
277,Satrio Suwantoro,Penerapan Metode clustering dengan\n k – means...,"Novi Prastiti. S.kom,. M.kom.",,Kabupaten Bangkalan merupakan salah satu kabup...,Bangkalan is one of the districts that have ma...
278,Miftahor Rahman,SISTEM INFORMASI GEOGRAFIS PELAYANAN KESEHATAN...,"Novi Prastiti, S.Kom., M.Kom",,Pelayanan sebagai proses pemenuhan kebutuhan m...,Service as a process of fulfilling needs throu...
279,Moh Ilham Ramdhan Fajrin,SISTEM PAKAR DIAGNOSA PENYAKIT MATA DENGAN MEN...,"Mohammad Syarief, S.T,. M.Cs.","Mohammad Syarief, S.T,. M.Cs.",ABSTRAK\n\nMata merupakan salah satu dari panc...,ABSTRACT The eye is one of the five senses whi...

### Teknik Multimedia dan Jaringan

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def multimediajaringan():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 28):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/19/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("multimediajaringan.csv", index=False)

    return df

In [ ]:
multimediajaringan()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Achmad Husaini,Elektronik Pemilihan Kepala Desa Menggunakan M...,"Aeri Rachmad, ST. MT.",,ABSTRAK\r\n\r\nPerkembangan teknologi informas...,ABSTRACT\r\n\r\nThe development of information...
1,FIKRI MUJADDIDI ALHAK,DIGITAL INFORMATION ASSISTANT,"AERI RACHMAD, ST., MT",,Media informasi kini perkembangannya sangat pe...,Media information is now very rapid developmen...
2,artika frida nirmala,perancangan aplikasi female e-healthy untuk de...,"Aeri Rachmad ST, MT",,Kanker serviks merupakan kanker terganas yang ...,Cervical cancer is a vicious cancer caused by ...
3,Ahmad Rivai,SISTEM INFORMASI TUGAS AKHIR PRODI TEKNIK MULT...,"Riza Alfita. S.T.,M.T.",-,Prodi teknik Multimedia dan Jaringan adalah sa...,Multimedia and Network engineering is one of t...
4,Idrus Tamam,APLIKASI PETA WISATA DIGITAL BANGKALAN DENGAN\...,"Aeri Rachmad, S.T.,M. T",,Pemerintah Indonesia telah berupaya meningkatk...,The Indonesian government has worked to increa...
...,...,...,...,...,...,...
126,Aunur Rofiq,APLIKASI SISTEM PENDUKUNG KEPUTUSAN TERHADAP P...,"M. Ali Syakur, S.Si., M.T.",,Penyakit THT (Telinga Hidung dan Tenggorokan) ...,ENT disease (Ear Nose and Throat) is a disease...
127,Rehadian Teja Sukmana Putra,Sistem Informasi Pangkalan Data Garam di Pulau...,"Ach. Khozaimi, S.Kom., M.Kom",,Garam merupakan salah satu komoditi besar Indo...,Salt is one of Indonesia's major commodities. ...
128,Ginanjar Eka Poetra,RANCANG BANGUN SISTEM INFORMASI KEUANGAN “DEP...,"M. Ali Syakur, S.Si., M.T",,Proses perkembangan sebuah usaha tidak akan le...,The process of development of a business will ...
129,Rizky wara setyawan,RANCANG BANGUN APLIKASI DIAGNOSIS PENYAKIT SAP...,Devie Rosa Amanisa,,Peternak sapi sering mengalami kesulitan dala...,Cattle ranchers often have difficulty in findi...
130,Muhammad Siswandi,Sistem Pakar Diagnosis Penyakit Unggas Menggun...,"Devie Rosa Anamisa. S.Kom., M.Kom",,Unggas adalah jenis hewan ternak kelompok bur...,Poultry is a type of livestock bird group that...

### Mekatronika

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def mekatronika():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 29):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/20/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("mekatronika.csv", index=False)

    return df

In [ ]:
mekatronika()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Moh. Amin Wahyudi,PERANCANGAN INJECTOR CLEANER DAN TESTER PADA S...,"Hairil Budiarto, S.T., MT.",,ABSTRAK\r\nSepeda motor menggunakan sistem inj...,ABSTRACT\r\nMotorcycle injection system is cur...
1,DWI NUGROHO,PROTOTYPE ALAT PEMBERI PAKAN\r\nAYAM PETELUR O...,"Muhammad Fuad, S.Kom. , MT.","Mirza Pramudia, ST. , M.Eng.",Peternakan merupakan salah satu bidang usaha y...,Livestock is one of the promising areas of bus...
2,Rezky Septian Akbar,pengukur tinggi badan berbasis arduino,"Ahmad Sahru Romadhon, S.Kom., M.T.",,Perkembangan ilmu pengetahuan teknologi yang m...,The development of modern technology science h...
3,Rio Tri Susanto,PEMODELAN SISTEM INFORMASI KETERSEDIAAN RUANG ...,"Muhammad Latif, S.T., M.T",,Pengaturan parkir yang sampai saat ini masih b...,Mostly parking arrangement was done manually u...
4,Moh. Iswahyudinorrahman,Desain Sistem pengendali Pintu otomatis Menggu...,"ahmad Sahru Romadhon, S.KOM., M.T.",,Pada zaman globalisasi mendorong teknologi unt...,At globalization epoch push technology to rapi...
...,...,...,...,...,...,...
132,Agus Dian Prayana,JAM BERBICARA UNTUK TUNA NETRA,"SRI WAHYUNI,S.KOM.M.T",,Indera penglihatan adalah salah satu sumber in...,The senses of detection are one of the main in...
133,Rifki Masfuddin,Alat daur ulang kertas menjadi bubur kertas (p...,"Vivi Tri Widyaningrum, S.Kom., M.T.",,Daur ulang limbah kertas adalah proses untuk m...,Waste paper recycling is a process to utilize ...
134,Yudiono,Alat Penyiram Bawang Merah Otomatis Untuk Meng...,"Sri Wahyuni, S.Kom, M.T.",,Bawang merah merupakan sayuran rempah yang cuk...,Shallots are spice vegetables that are quite p...
135,Jundullah Abdul Aziz M.,PROTOTIPE KONVEYOR BERBASIS METAL DETEKSI MAGN...,"Sri Wahyuni, S.Kom., M.T",,Keunggulan dalam bidang teknologi di era moder...,Excellence in the field of technology in the m...
136,Satria Jaya Rizaldy,PROTOTYPE PEMERIKSA BUTA WARNA,"Hairil Budiarto., S.T., M.T",,ABSTRAK\n\nPenelitian ini bertujuan untuk memb...,ABSTRACT\n\nThis study aims to build a color b...

### Teknik Elektro

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def elektro():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 35):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/23/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("elektro.csv", index=False)

    return df

In [ ]:
elektro()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Achmad Faidi,RANCANG BANGUN PENGATUR TEGANGAN OTOMATIS PADA...,"Koko Joni. S.T., M.Eng.","Achmad Fiqhi Ibadillah, S.T., M.Sc.",Tegangan yang tidak stabil dapat merusak peran...,Unstable voltages can damage electronic device...
1,Dandi Fathur Rohim,SMART GARBAGE BERBASIS INTERNET OF THINGS,"Haryanto. S.T., M.T","Koko Joni. S.T., M.Eng",Sampah di Indonesia merupakan suatu masalah ya...,Trash is one of serious prroblems in Indonesi....
2,Reynanda Bagus Widyo Astomo,Perancangan dan Pembuatan Stop Kontak Berbasis...,,,Pengunaan perangkat elektris dalam kehidupan s...,The use of electrical devices in everyday life...
3,Moh.Nazilus Sa’din Romdloni,PROTOTYPE SISTEM MONITORING DAN PENGENDALIAN P...,"Haryanto,ST,.MT","Riza Alfita,ST,.MT",Indonesia merupakan negara dengan curah hujan ...,Indonesia known as the country with heavy rain...
4,Fajar Dwima Wijaya,Rancang Bangun Sistem Keamanan Parkir Berbasis...,"Diana Rahmawati, S.T., M.T","Kunto Aji Wibisono, S.T., M.T",Sistem pengelolaan tempat parkir pada saat ini...,Parking management system at this time is stil...
...,...,...,...,...,...,...
162,Prayogo Teguh Wibowo,Implementasi Convolutional Neural Network Untu...,"Koko Joni, S.T., M.Eng","Achmad Fiqi Ibadillah, S.T., M.Sc",Informasi teks merupakan salah satu komponen p...,
163,KHOLIFATUL SADHIAH,OPTIMALISASI KINERJA PSTN KE VOIP DENGAN MIGRA...,"Ahmad Ubaidillah Ms.,S.T.,MT.","Haryanto, S.T., M.T.",Public Switched Telephone Network (PSTN) adala...,Public Switched Telephone Network (PSTN) is a ...
164,Tantra Juang Ilhami,MONITORING BAHAN BAKAR GENERATOR DENGAN MENGGU...,"Miftachul Ulum ST,.MT.","Riza Alfita, S.T., M.T.",Pemakaian energi listrik semakin lama semakin ...,The use of electricity is increasing as all jo...
165,ACHMAD NUR RIVAI,RANCANGAN SISTEM MOBILE ROBOT SOUND LOCALIZATI...,"DIANA RAHMAWATI,ST.,M.T.","ACHMAD FIQHI IBADILLAH,S.T.,M.Sc",Sistem kontrol robot beroda pada umumnya berbe...,Wheeled robot control systems generally take t...
166,Noer Indra Afriansya,APLIKASI PENGENALAN INFORMASI OBJEK BERSEJARAH...,"Miftachul Ulum, S.T., M.T.","Riza Alfita, S.T., M.T.",Museum Keraton Sumenep merupakan salah satu de...,Sumenep Palace Museum is a destination that is...

### Sistem Informasi

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def sisfor():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 2):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/31/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("sisfor.csv", index=False)

    return df

In [ ]:
sisfor()

Empty DataFrame
Columns: [penulis, judul, pembimbing_pertama, pembimbing_kedua, abstrak_indo, abstrak_inggris]
Index: []

### Teknik Mesin

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def mesin():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 2):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/32/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("mesin.csv", index=False)

    return df

In [ ]:
mesin()

Empty DataFrame
Columns: [penulis, judul, pembimbing_pertama, pembimbing_kedua, abstrak_indo, abstrak_inggris]
Index: []

### Teknik Mekatronika

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def teknikmekatro():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 4):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/33/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("teknikmekatro.csv", index=False)

    return df

In [ ]:
teknikmekatro()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Mochamad Izar Bahroni,Kestabilan Autonomous Quadcopter Dengan Kontro...,"Sri Wahyuni, S.Kom., M.T","Faikul Umam, S.Kom., M.T",Unmanned Aerial Vehicle (UAV) memiliki banyak ...,"Unmanned Aerial Vehicle (UAV) has many uses, i..."
1,Moch Zaini,perancangan dan pembuatan sistem rem elektrik ...,"Hairil Budiarto., ST.MT","Faikul Umam., S.Kom.,MT",Kendaraan merupakan suatu alat yang banyak dig...,Vehicle is a tool that is widely used by human...
2,Mohammad Syafruddin,Pengatur Kerapatan Kertas Pada Alat Penggulung...,"Faikul Umam S.Kom., M.T","Ahmad Sahru Romadhon S.Kom., M.T",PT PAKERIN adalah salah satu pabrik kertas ter...,PT PAKERIN is one of the largest paper mills i...
3,"Khanif Khoirul Umam, A.Md.",IMPLEMENTASI ALGORITMA MAZE MAPPING PENCARIAN ...,"Sri Wahyuni, S.Kom., M.T.","Hairil Budiarto, S.T.,M.T.",Robot shortest path merupakan jenis robot yang...,Shortest path robot is a type of robot that is...
4,Achmad Ayubal Ansori,Alat Pengering Rumput Laut Menggunakan Metode ...,"Ahmad Sahru R.,S.Kom.,M.T","Hairil Budiarto S.T.,M.T",Rumput laut merupakan tumbuhan laut yang banya...,Seaweed is a marine plant widely cultivated by...
5,Raudatul Jannah,ROBOT PENDETEKSI LOKASI KEBOCORAN PADA PIPA LI...,"Vivi Tri .W, S.Kom.,MT.","Hairil Budiarto,ST.,MT.",LPG adalah singkatan dari Liquefied Petroleum ...,LPG stands for Liquefied Petroleum Gas which m...
6,Ach. Dafid,SISTEM KENDALI KADAR Ph DAN TEMPERATUR TAMBAK ...,"Vivi Tri Widyaningrum, S.Kom.,M.T.","Hairil Budiarto,S.T.,M.T.",Komoditas hewan air yang mampu mengahasilkan d...,Animal water commodities capable of producing ...
7,MOH HOLIL,PERANCANGAN PROTOTIPE ALAT PENUKAR \nPANAS MEN...,"AHMAD SAHRU ROMADHON.,S.Kom.MT","HAIRIL BUDIARTO.,ST.MT",Perancangan Prototype alat ini dilakukan karen...,Prototype design tool is done because the medi...
8,Ach Imam Sudianto,PEMANFAATAN ANTI-ROLL TERHADAP KESEIMBANGAN KAPAL,"Hairil Budiarto S.T., M.T","Vivi Tri Widyanningrum S.Kom., M.T.",Kapal adalah alat transportasi pengangkut penu...,The ship is a means of transporting passengers...
9,MOH TAUFIK HIDAYAT,ALAT PENGGULUNG UNTUK MENGATUR KERAPATAN KERTA...,"FAIKUL UMAM., S.KOM., M.T","SRI WAHYUNI., S.KOM., M.T",ABSTRAK\n\nKertas merupakan kebutuhan yang dib...,ABSTRACT\n\nPaper is a necessity needed by hum...
10,Alvian Ainun Fajrih,Optimasi Penguapan Air Laut Tua Pada Rumah Kaca,"Hairil Budiarto, S.T., M.T.","Faikul Umam, S.Kom., M.T.",Pembuatan garam di Madura umumnya dilakukan de...,Making salt in Madura is generally done by hea...
11,ADINDA DEBTIANA DWIKA HILDA,KESTABILAN KECEPATAN MOBILE ROBOT PADA LINTASA...,"Faikul Umam, S.Kom., M.T.","Sri Wahyuni, S.Kom., M.T.",Mobile robot merupakan salah satu kategori rob...,Mobile robot is one of the robot categories th...
12,Nafizatul Jamilah,Rancang Bangun Sistem Otomasi Robot Pengecatan...,"Hairil Budiarto, S.T., M.T","Sri Wahyuni, S.Kom., M.T",ABSTRAK\n\nMarka jalan raya adalah sebuah tand...,ABSTRACT\n\nA highway mark is a sign that can ...
13,Agus Salim,Sistem Kestabilan Gerak Robot Omnidirection Me...,"Vivi Tri W, S.Kom., M.T","Ahmad Sahru R, S.Kom., M.T",Di era globalisasi ini sangatlah mungkin tekno...,"In this globalization era, it is very possible..."

## Ilmu Sosial Dan Ilmu Budaya

### Sosiologi

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def sosiologi():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 137):
        print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/12/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("sosiologi.csv", index=False)

    return df

In [ ]:
sosiologi()

📄 Memproses halaman ke-1
📄 Memproses halaman ke-2
📄 Memproses halaman ke-3
📄 Memproses halaman ke-4
📄 Memproses halaman ke-5
📄 Memproses halaman ke-6
📄 Memproses halaman ke-7
📄 Memproses halaman ke-8
📄 Memproses halaman ke-9
📄 Memproses halaman ke-10
📄 Memproses halaman ke-11
📄 Memproses halaman ke-12
📄 Memproses halaman ke-13
📄 Memproses halaman ke-14
📄 Memproses halaman ke-15
📄 Memproses halaman ke-16
📄 Memproses halaman ke-17
📄 Memproses halaman ke-18
📄 Memproses halaman ke-19
📄 Memproses halaman ke-20
📄 Memproses halaman ke-21
📄 Memproses halaman ke-22
📄 Memproses halaman ke-23
📄 Memproses halaman ke-24
📄 Memproses halaman ke-25
📄 Memproses halaman ke-26
📄 Memproses halaman ke-27
📄 Memproses halaman ke-28
📄 Memproses halaman ke-29
📄 Memproses halaman ke-30
📄 Memproses halaman ke-31
📄 Memproses halaman ke-32
📄 Memproses halaman ke-33
📄 Memproses halaman ke-34
📄 Memproses halaman ke-35
📄 Memproses halaman ke-36
📄 Memproses halaman ke-37
📄 Memproses halaman ke-38
📄 Memproses halaman ke-39
📄 Memproses halaman ke-40
📄 Memproses halaman ke-41
📄 Memproses halaman ke-42
📄 Memproses halaman ke-43
📄 Memproses halaman ke-44
📄 Memproses halaman ke-45
📄 Memproses halaman ke-46
📄 Memproses halaman ke-47
📄 Memproses halaman ke-48
📄 Memproses halaman ke-49
📄 Memproses halaman ke-50
📄 Memproses halaman ke-51
📄 Memproses halaman ke-52
📄 Memproses halaman ke-53
📄 Memproses halaman ke-54
📄 Memproses halaman ke-55
📄 Memproses halaman ke-56
📄 Memproses halaman ke-57
📄 Memproses halaman ke-58
📄 Memproses halaman ke-59
📄 Memproses halaman ke-60
📄 Memproses halaman ke-61
📄 Memproses halaman ke-62
📄 Memproses halaman ke-63
📄 Memproses halaman ke-64
📄 Memproses halaman ke-65
📄 Memproses halaman ke-66
📄 Memproses halaman ke-67
📄 Memproses halaman ke-68
📄 Memproses halaman ke-69
📄 Memproses halaman ke-70
📄 Memproses halaman ke-71
📄 Memproses halaman ke-72
📄 Memproses halaman ke-73
📄 Memproses halaman ke-74
📄 Memproses halaman ke-75
📄 Memproses halaman ke-76
📄 Memproses halaman ke-77
📄 Memproses halaman ke-78
📄 Memproses halaman ke-79
📄 Memproses halaman ke-80
📄 Memproses halaman ke-81
📄 Memproses halaman ke-82
📄 Memproses halaman ke-83
📄 Memproses halaman ke-84
📄 Memproses halaman ke-85
📄 Memproses halaman ke-86
📄 Memproses halaman ke-87
📄 Memproses halaman ke-88
📄 Memproses halaman ke-89
📄 Memproses halaman ke-90
📄 Memproses halaman ke-91
📄 Memproses halaman ke-92
📄 Memproses halaman ke-93
📄 Memproses halaman ke-94
📄 Memproses halaman ke-95
📄 Memproses halaman ke-96
📄 Memproses halaman ke-97
📄 Memproses halaman ke-98
📄 Memproses halaman ke-99
📄 Memproses halaman ke-100
📄 Memproses halaman ke-101
📄 Memproses halaman ke-102
📄 Memproses halaman ke-103
📄 Memproses halaman ke-104
📄 Memproses halaman ke-105
📄 Memproses halaman ke-106
📄 Memproses halaman ke-107
📄 Memproses halaman ke-108
📄 Memproses halaman ke-109
📄 Memproses halaman ke-110
📄 Memproses halaman ke-111
📄 Memproses halaman ke-112
📄 Memproses halaman ke-113
📄 Memproses halaman ke-114
📄 Memproses halaman ke-115
📄 Memproses halaman ke-116
📄 Memproses halaman ke-117
📄 Memproses halaman ke-118
📄 Memproses halaman ke-119
📄 Memproses halaman ke-120
📄 Memproses halaman ke-121
📄 Memproses halaman ke-122
📄 Memproses halaman ke-123
📄 Memproses halaman ke-124
📄 Memproses halaman ke-125
📄 Memproses halaman ke-126
📄 Memproses halaman ke-127
📄 Memproses halaman ke-128
📄 Memproses halaman ke-129
📄 Memproses halaman ke-130
📄 Memproses halaman ke-131
📄 Memproses halaman ke-132
📄 Memproses halaman ke-133
📄 Memproses halaman ke-134
📄 Memproses halaman ke-135
📄 Memproses halaman ke-136

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Arief Barawijaya,STRATEGI ADAPTASI PEDAGANG MAKANAN TRADISIONAL...,"Drs. Subandri, M.S","Arie Wahyu Prananta, S.Pi., M.Sos","RINGKASAN\r\nArief Barawijaya, NIM. 08.05.2.1....","ABSTRACT\r\n\r\n\r\nBarawijaya, Arief. NIM. 08..."
1,sabri,TRADISI PERTUNANGAN PADA USIA DINI\r\n( Studi ...,"Drs. Subandri., M.S","Dr. Sri Hidayati., M.Si.",ABSTRAK\r\nPenelitian ini berjudul “Tradisi Pe...,"ABSTRACT\r\n\tThe research entitle ""Engagement..."
2,syarif hidayatullah,DINAMIKA PERSAINGAN PERAN KIAI DAN BLATER DALA...,"syamsu budiyanti, S.sos, M.si","iskandar dzulkarnain, S.Thi, M.si",ABSTRAK\r\nSyarif Hidayatullah NIM. 07.01.211....,ABSTRACT \r\nSyarif Hidayatullah NIM 07.01.211...
3,Rusli,FENOMENA JUDI MELALUI MIG33\r\nPADA MASYARAKAT...,"Syamsu budiyanti, S.Sos. M.Si",Arie Wahyu P. S.Pi. M.Si,FENOMENA JUDI MELALUI MIG33 \r\nPADA MASYARAKA...,"ABSTRACT\r\nSociology Studies Program, Faculty..."
4,MAHMUD,Konstruksi Sosial Predikat Haji (Studi Kasus D...,"Drs. Subandri, M.S","Iskandar Dzulkarnain, S.Th.I., M.Si","ABSTRAK\r\nMahmud, NIM. 08.05.2.1.2.000.02, Pr...","ABSTRACT\r\nMahmud, NIM. 08.05.2.1.2.000.02, S..."
...,...,...,...,...,...,...
672,Alfiah Nur Rohmah,Makna Bhubuhan Sebagai Bentuk Pelunasan Hutang...,"Dr. Arie Wahyu Prananta, S.Pi, M.Sos",,Tujuan dari penelitian ini adalah untuk menget...,The purpose of this study is to find out how t...
673,Ayu Aprilia Puji Lestari,STRATEGI PENGUATAN KEPERCAYAAN\n( Studi Pada P...,"Bangun Sentosa Dwi Haryanto., S.Sos., M.Si., Ph.D",,"Abstrak - Ayu Aprilia Puji Lestari, NIM 160521...","Abstract - Ayu Aprilia Puji Lestari, NIM 16052..."
674,mohammad sa'nun fauzi,BENTUK PERLAWANAN MASYARAKAT TERHADAP GALIAN C...,"Khoirul Rosyadi, SS., M.Si., Ph.D",,Tujuan dari penelitian ini adalah untuk mengam...,The purpose of this study is to describe and e...
675,Citra Zelyn Pratiwi,Strategi Bertahan Hidup Buruh Tani Wanita Dala...,"Dr. Arie Wahyu Prananta, S.Pi,.M.sos",,ABSTRAK \nTujuan dari penelitian ini yaitu unt...,ABSTRACK \nThe purpose of this study is to fin...
676,RIAN PANDI PRANATA,Analisis Wacana Media Online Detik.com dalam M...,"Dr. Arie Wahyu Prananta, S.Pi.,M.Sos.,",,Abstrak\n\n Rian Pandi Pranata. NIM 1605211000...,ABSTRACT\n\n Rian Pandi Pranata. NIM 160521100...

### Ilmu Komunikasi

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def ilkom():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 136):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/13/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("ilkom.csv", index=False)

    return df

In [ ]:
ilkom()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,MUHAMMAD MOHED,STRATEGI KOMUNIKASI PEMASARAN KOPERASI SIMPAN ...,"Netty Dyah Kurniasari, S.Sos, M.Med.Kom","Muhtar Wahyudi, S.Sos, MA",ABSTRAKSI\r\n\r\nSTRATEGI KOMUNIKASI PEMASARAN...,ABSTRACT \r\n\r\nMARKETING COMMUNICATION STRA...
1,Lely Faizatun Masfufa,Pengaruh Terpaan Iklan Hilo Teen Versi Dance t...,"Nikmah Suryandari,S.Sos, M.Si","Dinara Maya Julijanti,S.Sos, M.Si",ABSTRACT\r\nState Senior High School 1 Surabay...,ABSTRAK\r\nSMA Negeri 1 Surabaya adalah sa...
2,AGUS PRAMONO,"“MAKNA, TRADISI DAN SIMBOL DALAM UPACARA ROKAT...","DINARA MAYA JULIJANTI, S.Sos, M.Si","TATAQ HANDAKA, S.Sos, M.Si","ABSTRAK\r\nAgus Pramono, NIM. 08.05.3.1.1.000....","ABSTRACT\r\nAgus Pramono, NIM. 08. 05.3.1.1. ..."
3,Delfriska Novawati Panjaitan,REPRESENTASI NILAI-NILAI BUDAYA LOKAL KOREA ME...,"Netty Dyah K, S.Sos., M.Med.Kom","Dewi Quraisyin, S.Pdi., M.Si",REPRESENTASI NILAI-NILAI BUDAYA LOKAL KOREA ME...,REPRESENTATION THE VALUES OF KOREAN CULTURE FR...
4,Bravo Jaya Pramono Sinaga,KONSTRUKSI TRADISI MUSLIM SURABAYA MELALUI ISI...,"Surokim, S.Sos., M.Si.","Dessy Trisilowaty, S.Sos., M. Si.",TV9 Surabaya adalah media massa milik NU yang ...,TV9 Surabaya is mass media own the NU presenti...
...,...,...,...,...,...,...
669,Aini Wulandari,Komunikasi Antar Blater dalam Tradisi Remoh se...,"Dr. Bani Eka Dartiningsih, S.Sos., MSi","Dr. Yuliana Rakhmawati, S.Sos., M.Si",ABSTRAK\n\nRemoh blater diadakan untuk berkump...,ABSTRACT\n\nThe Remoh of the blater was held f...
670,Riski Hakiki,Bias Gender Jurnalis Perempuan Di Media Massa ...,"Dr. Yuliana Rakhmawati, S.Sos., M.Si",,Penelitian ini berjudul Bias Gender Jurnalis P...,This research is titled Gender bias of Women j...
671,RINDA DWI PRADINA,SUPPORTIVENESS SINGLE FATHER DALAM MEMBANGUN H...,"Dr.Yuliana Rakhmawati, S.Sos.,M.Si.",-,"ABSTRAK\nRinda Dwi Pradina 160531100026, Progr...","ABSTRACT\nRinda Dwi Pradina 160531100026, Comm..."
672,Ayu Fitria,KOMUNIKASI PEMASARAN WISATA BUKIT JADDIH BANGK...,"R. Bambang Moertijoso, S,Sos., M.Si.","Imam Sofyan, S.Sos., M.Si.",ABSTRAK\n\nTujuan utama dari penelitian ini ad...,ABSTRACT\n\nThe main purpose of this research ...
673,Rina Astaria Mendrova,Fenomenologi Relawan Kelompok Dukungan Sebaya ...,"Dr. Yuliana Rakhmawati, S.Sos., M.Si.",-,Abstrak - Tujuan dari penelitian ini adalah me...,Abstract - The purpose of this study is to fin...

### Psikologi

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def psikologi():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 105):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/14/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("psikologi.csv", index=False)

    return df

In [ ]:
psikologi()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Badrus Syamsi,Pengaruh Kompetensi Profesional Guru terhadap ...,"Alifah Rahma Wati. S.Psi., M.Psi","Zainal Abidin. S.Psi., M.Si","Guru yang berkualitas, berkompetensi profesion...","Qualified teachers, professional competence, w..."
1,Umarul Faruk,Perbedaan Tingkat Kemandirian dan Prestasi Bel...,"Zainal Abidin. S.Psi., M.Si","Nur Aziz Afandi. S.Psi., M.Si",Kemandirian merupakan salah satu faktor penduk...,Independence is one of the contributing factor...
2,TONI TRIATMOKO,Pengaruh Kecerdasan Emosional terhadap Culture...,"HERA WAHYUNI, M.Psi., Psi.","ZAINAL ABIDIN, S.Psi., M.Si.",Penelitian ini bertujuan untuk mengetahui adan...,This study aims to understand the influence of...
3,ROKIP,RISK-TAKING BEHAVIORS KAUM ELITE BLATER\r\nDI ...,"Yan Ariyani, M.Psi., Psi","Alifah Rahma Wati, M.Psi.,Psi",Penelitian ini bertujuan untuk mendeskripsikan...,This study aims to understand the description ...
4,JUJUK EKO WAHYUDI,Etos Kerja Tukang Rawat Sapi Karapan Madura (S...,"Yan Ariyani S.Psi., M.Psi., Psi.","Alifah Rahma Wati S.Psi, M.Psi, Psi.",Penelitian ini bertujuan untuk mengetahui Etos...,This study aimed to determine the working etho...
...,...,...,...,...,...,...
512,Crusita Widya Anggraeni,SELF COMPASSION PADA SURVIVOR HIV-AIDS DENGAN ...,"Alifah Rahma Wati S.Psi., M.Psi., Psikolog",,Penelitian ini bertujuan mengetahui self compa...,This study aims to determine the self-compassi...
513,ALIFIYA RIZKI LAILY,HUBUNGAN ANTARA PROKRASTINASI AKADEMIK DENGAN ...,"Fandi Rosi Sarwo Edi, S.K.M., S.Psi., M.Psi",,Penelitian ini bertujuan untuk mengetahui hubu...,This study aims to determine the relationship ...
514,SEPTIANA CAHYANINGRUM,INTIMACY AYAH (SINGLE PARENT) TERHADAP ANAK PE...,"YAN ARIYANI, S. PSI., M. PSI., PSIKOLOG",,ABSTRAK\nPenelitian ini bertujuan untuk menget...,ABSTRACT\nThis study aims to describe intimacy...
515,ISROH DWI NURLITA,HUBUNGAN NILAI SOSIAL DENGAN PERILAKU ALTRUISM...,"FANDI ROSI SARWO EDI, S.K.M., S.Psi., M.Psi",,Mayarakat relawan Indonesia (MRI) Surabaya ter...,The Indonesian volunteer society (MRI) Surabay...
516,Siti Komariyah,Perbedaan Kebahagaiaan Pasangan Pernikahan Per...,Dr. Netty Herawati. Psikolog,,Siti Komariyah. 130541100133. Perbedaan kebaha...,Siti Komariyah. 130541100131. The difference b...

### Sastra Inggris

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def sasing():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 134):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/15/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("sasing.csv", index=False)

    return df

In [ ]:
sasing()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,a'isyah,A Study of Language Variety on Facebook Status,"Iqbal Nurul Azhar, SS.,M.Hum.","Diah Ikawati A.,SS.,M.Pd.",ABSTRACT\r\n\r\nAisyah. 08.05.111.00018. A Stu...,ABSTRACT\r\n\r\nAisyah. 08.05.111.00018. A Stu...
1,Atik Husnia,A study of Conjunction Translation in the nove...,"Sriyono, SS.,M.Hum","Rosyida Ekawati, SS.MA","ABSTRACT\r\n\r\nHusnia, Atik. 08.05.111.00017....","ABSTRACT\r\n\r\nHusnia, Atik. 08.05.111.00017...."
2,Mochammad Hanif,The Universal Narrative Structure in John Stei...,"Imron Wakhid Harits, SS., M.Pd.","Rifah Inayati, SS., MA.",,"ABSTRACT\r\n\r\nHanif, Mochammad. 08.05.111.00..."
3,Deny Andrianto,A Study of Conversational Implicature Uttered ...,"Sriyono, SS., M.Hum","Iqbal Nurul Azhar, SS., M.Hum","ABSTRACT\r\n\r\nAndrianto, Deny. 08.05.111.000...","ABSTRACT\r\n\r\nAndrianto, Deny. 08.05.111.000..."
4,Tri Maryono,Lady Macbeth's Somnambulism in Shakespeare's M...,Dr. Suryo Tri Saksono,"Suci Suryani, S.S., M.Pd",,"ABSTRACT\r\n\r\nMaryono, Tri. 06.05.1.1.1.0000..."
...,...,...,...,...,...,...
660,Dewi Retno Indawati,Multimodal Analysis of Promotional Video in Lo...,"Dr. Rosyida Ekawati, S.S., M.A",,Penelitian ini bertujuan untuk meneliti tentan...,The study aimed to explain the representation ...
661,Meliya Intan Sari,CHARACTER AND PLOT DEVELOPMENT IN ALICE MUNRO’...,"Zakiyatul Mufidah, S.Hum., M.Hum.","Zakiyatul Mufidah, S.Hum., M.Hum.","ABSTRAK\n\nSari, Meliya Intan. 13.05.111.00068...","ABSTRACT\n\nSari, Meliya Intan. 13.05.111.0006..."
662,Dyanatul Mustaqimah,An Acoustic Analysis of English Vowels Produce...,"Misnadin, S.S., M.A., Ph.D",,,"This study focused on the English vowels [æ], ..."
663,NAFILATUN NASUHA,AN ANALYSIS OF PERSONAL PRONOUNS IN DONALD TRU...,"Dr. Rosyida Ekawati, S.S., M.A",,ABSTRACT\n\nNafilatun Nasuha. 160511100005. An...,ABSTRACT\n\nNafilatun Nasuha. 160511100005. An...
664,Sulfi Amalia,AN ANALYSIS OF CATEGORY SHIFT IN THE ENGLISH T...,"Dr. Masduki, M.Pd",,Sulfi Amalia. 15.05.111.00021. English Study P...,Sulfi Amalia. 15.05.111.00021. English Study P...

## Keislaman

### Ekonomi Syariah

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def ekosyariah():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 114):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/16/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("ekosyariah.csv", index=False)

    return df

In [ ]:
ekosyariah()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,MOH. MUHLIS ANWAR,“PENERAPAN SHARIA MARKETING MIX DALAM MENINGK...,"LAILATUL QADARIYAH, S.H.I, M.E.I",-,ABSTRAK\r\nPenelitian ini akan membahas tentan...,ABSTRACT\r\nThis research is going to discuss ...
1,Fatima,"Pengaruh Biaya Ijarah, Prosedur Pencairan dan ...","Lailatul Qadariyah, S.HI., M.EI",,Penelitian yang berjudul pengaruh biaya ijarah...,The research is entitled the impact of ijarah ...
2,VIVID NUR LAILI,TINJAUAN EKONOMI ISLAM TERHADAP PENGUPAHAN KAR...,"Dr. Abdur Rohman, S.Ag.,M.E.I NIP. 19740815200...",,Penelitian ini akan membahas tentang tinjauan ...,This research will discuss the Islamic Economi...
3,Ana Ayu Arbaatus Sholichah,Pengaruh Pembiayaan Murabahah terhadap Pemberd...,"Dr.Abdur Rohman, S.Ag.,M.EI",-,Penelitian yang berjudul pengaruh pembiayaan M...,The study entitled influence Murabahah financi...
4,Imroatul Azizah,Analisis Persepsi dan Respon Pedagang Muslim t...,"Dony Burhan Noor Hasan L.C.,M.A",,Lembaga Keuangan Syariah non bank yang keberad...,Perception and Response Analysis of the Existe...
...,...,...,...,...,...,...
556,Fajar Dianti Khoeroh Saadah,"Pengaruh Asset Growth, Current Ratio, dan Debt...","Dahruji, S.E., M.E.I",,Nilai perusahaan merupakan bagian terpenting y...,Company value is the most important part that ...
557,Siti Amina,Analisis Tingkat Literasi Zakat Masyarakat di ...,"Dr. Abdur Rahman, S.Ag., M.E.I.",,"Literasi zakat merupakan pengetahuan, keteramp...","Zakat literacy is knowledge, skills and belief..."
558,Ma'ruf Sya'roni,PENGARUH KUALITAS PRODUK DAN HARGA TERHADAP KE...,"Dzikrulloh, S.EI., M.SEI",,ABSTRAK\nTujuan penelitian ini adalah untuk me...,ABSTRACT\nThe purpose of this research is to k...
559,Rofiatul Zuhria,Model pemberdayaan ekonomi masyarakat melalui ...,"Dr.Abdur Rahman, S. Ag., M.E.I.",,Kedai kopi sampah merupakan salah satu usaha y...,The junk coffee shop is one of the businesses ...
560,HENI ROSIDAH,ANALISIS MANAJEMEN PENGELOLAAN WAKAF TUNAI PRO...,"DR. ABDUR ROHMAN, S.AG., M.E.I.",,Penelitian ini dilatar belakangi oleh adanya B...,This research is motivated by the existence of...

### Hukum Bisnis Syariah

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def HBS():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 84):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/17/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("HBS.csv", index=False)

    return df

In [ ]:
HBS()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,MUHAMMAD HENDRIK,PENETAPAN UJROH DI PEGADAIAN SYARIAH BANGKALAN...,"H. ACH. MUS'IF, S.HI., MA",,,
1,nuruddin,tinjauan hukum Islam terhadap penerapan denda ...,shofiyun nahidloh,,Transaksi pinjam meminjam buku diperpustakaan ...,ABSTRACT\r\nThe library book lending and borro...
2,Sumar Rohman,Konversi Gadai Menjadi Nilai Daging Sapi Persp...,"Shofiyun Nahidloh, S. Ag., M.HI",,ABSTRAK\r\nGadai ini merupakan bagian dari pra...,ABSTRACT\r\nThe pawn is a part of Muamalah pra...
3,RUMSIYAH,TINJAUAN HUKUM ISLAM TERHADAP TRADISI PENGURAN...,"SHOFIUN NAHIDLOH,S.Ag.,M.HI",,ABSTRAK\r\nTimbangan merupakan jenis pengukura...,ABSTRACT\r\nScales is the tool to gauge someth...
4,Adam Malik,PRAKTEK PERMODALAN BERSYARAT MENURUT HUKUM ISL...,"Shofiyun Nahidloh,S.Ag.,M.HI",,ABSTRAK\r\n\tSkripsi ini adalah hasil peneliti...,ABSTRACT\r\n\tThis thesis is the result of a s...
...,...,...,...,...,...,...
409,Faizatun Nazila,TINJAUAN HUKUM ISLAM TERHADAP BISNIS JASA TRA...,"Shofiyun Nahidloh, S.Ag.,M.H.I",,Perbedaan harga yang diterapkan pemilik jasa t...,The price difference applied by the transporta...
410,Dwi Nisa'ul farihah,Tinjauan Sosiologi Hukum Islam Terhadap Prakti...,"Hamam, Lc., M.sy",,Skripsi yang berjudul tinjauan sosiologi hukum...,The thesis entitled the review of Islamic lega...
411,Mohammad Zaini,Tinjauan Maslahah Mursalah Tentang Putusan Ver...,"Shofiyun Nahidloh, S.Ag., M.H.I",,Pengadilan agama sebagai salah satu kekuasaan ...,The religious court as one of the judicial aut...
412,Halimah,ANALISIS INVESTASI SYARIAH DITINJAU DARI AL-MA...,"Mohammad Hipni, S.HI.,M.HI",,Skripsi ini bejudul “Analisis Investasi Syaria...,"This thesis entitled ""An Analysis of Sharia In..."
413,Imam Farodhi,Tinjauan Mas}lahah Terhadap Penetapan Fatwa No...,"Busro Karim, S.Hum.,M.Pd.I",,Musha>rakah Mutana>qis}ah merupakan sebuah aka...,Musha>rakah Mutana>qis}ah is a financing agree...

## Pendidikan

### PGSD

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def pgsd():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 184):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/18/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("pgsd.csv", index=False)

    return df

In [ ]:
pgsd()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Dessy Setyowati,Pengaruh Penggunaan Media Audio Visual Terhada...,"Drs. Harun Al Rasyid, M.Si","Wanda Ramansyah, S.Pd., M.Pd",Latar belakang penelitian ini adalah penggunaa...,The background of this study is the use of me...
1,Holiyah Sari,Strategi Sekolah dalam Upaya Penguatan Karakte...,"Mujtahidin, S.Pd., M.Pd","Moh. Edy Nurtamam, S.Pd., M.Si",Penelitian ini bertujuan untuk mengetahui gamb...,This research is conducted by purposed to find...
2,Dwi Indah Rahayuingsih,Perbandingan Hasil Belajar Cooperative Learnin...,"Eva Ari Wahyuni, S.Pd., M.Si","Muhammad Busyro Karim, S.Ag., M.Si",Penelitian “Perbandingan Hasil Belajar Coopera...,A Study about “Cooperative Learning Result Com...
3,Fatimatus Zakiyah,Kemampuan Berpikir Tingkat Tinggi Siswa Kelas ...,"Priyono Tri Febrianto, S.Sos., M.Si","Wahid Khoirul Ikhwan, M.Pd",Penelitian ini bertujuan untuk mengetahui kema...,The aim of this research is to know the Higher...
4,Diska Febriadi,Hubungan Antara Kemandirian Belajar dengan Has...,"Drs. Harun Al Rasyid, M.Si.","Muhammad Busyro Karim, S.Ag., M.Si.",Penelitian ini bertujuan untuk mengetahui hubu...,This reserach aims to know the relationship be...
...,...,...,...,...,...,...
908,ALDY ADITYA FABIAN YAHYA,PENGEMBANGAN MAJALAH BERBASIS GAME MOBILE LEGE...,"Fachrur Rozie, S.Pd.,M.Pd.","Bagus Rahmad Wijaya, S.Pd., M.Pd.",ABSTRAK\nTujuan penelitian pengembangan ini...,ABSTRACT\nThe purpose of this development rese...
909,Ratih Permatasari,PENGEMBANGAN PERANGKAT PEMBELAJARAN MODEL\nPRO...,"Rika Wulandari, S.Pd., M.Pd","Conny Dian Sumadi ,S.Pd., M.Pd",ABSTRAK\nPerangkat pembelajaran adalah bentuk ...,ABSRACT\nLearning tools are a form of teacher ...
910,Zuliya Safutri,Problematika Pembelajaran Daring Siswa Kelas R...,"Mahmud, S.IP., M.Si.","Nilamsari Damayanti Fajrin, S.Pd., M.Pd.",Tujuan dalam Penelitian ini adalah mengetahui ...,The purpose of this study is to determine the ...
911,Lyta Pranawati,PENDAMPINGAN ORANG TUA DALAM PROSES BELAJAR AN...,"Priyono Tri Febrianto, S.Sos., M.Si","Andika Adinanda Siswoyo, S.Pd., M.Pd",Abstrak\n\nTujuan dari penelitian ini yaitu un...,Abstract\n\nThe purpose of this study is to fi...
912,Leni Marlinda,peran Guru Dalam Menanamkan NIlai-Nilai Kearif...,"mahmud, S.IP.,M.Si.","Agung Setyawan, S.Pd.,M.Pd.",Abstrak\nPeran guru dalam melestarikan kebuday...,ABSTRACT\nThe role of the teacher in preservin...

### PBSI

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def pbsi():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 74):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/27/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("pbsi.csv", index=False)

    return df

In [ ]:
pbsi()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,MAULIDIYA IRAWATI,ANALISIS REGISTER BAHASA MADURA PADA MASYARAKA...,"Ira Fatmawati, S.S., M.Pd.","Ahmad Jami’ul Amil, M.Pd.",Abstrak: Penggunaan bahasa Indonesia pada masy...,Abstract: The use of Indonesian reviewed Torju...
1,Grasia Wahyu Kharisma,PENGARUH PENERAPAN METODE ROLE PLAYING BERBAN...,"Khusnul Khotimah, S.S., M.Pd.","Ahmad Jami'ul Amil, S.Pd., M.Pd.",Grasia Wahyu Kharisma. 2017. Pengaruh Penerapa...,Grasia Wahyu Kharisma. 2017. The Effect of Imp...
2,Tasrifah,MAKNA KONTEKSTUAL PADA JINGLE SLOGAN TELEVISI ...,"Khusnul Khotimah. S.S., M.Pd","Ahmad Jami'ul Amil, S.Pd.,M.Pd",Tasrifah. 2017. Makna Kontekstual Pada Jingle ...,Tasrifah. 2017. The contextual on the jingle s...
3,Nurdin,INTERFERENSI FONOLOGI BAHASA SUNDA DALAM PENGG...,"Khusnul Khotimah, S.S., M.Pd.","Ahmad Jami'ul Amil, S.Pd., M.Pd.",Penelitian ini bertujuan untuk mendeskripsikan...,This study has an objective to describe the fo...
4,Ulul Albabiyatul Husna,KESALAHAN SINTAKSIS PADA KARANGAN NARASI SISWA...,"Khusnul Khotimah, S.S., M.Pd.","Ahmad Jami’ul Amil, S.Pd., M.Pd.",Ulul Albabiyatul Husna. 2017. Kesalahan Sintak...,Ulul Albabiyatul Husna. 2017. Syntax Error in ...
...,...,...,...,...,...,...
360,Abdur Rochman Wahid,Analisis Penerapan Gambar “Augmented Reality” ...,"Abdul Rosid, S.Pd., M.Pd","Ahmad Jami'ul Amil, S.Pd., M.Pd",Abstrak: Media pembelajaran adalah media yang ...,Abstract: Learning media are media that contai...
361,MOHAMMAD NUR HIDAYATULLAH,ANALISIS MODEL PICTURE AND PICTURE MATERI CERI...,"SULAIMAN, S.Pd., M.Pd.","IKA FEBRIANI, S.S., M.Pd.",Abstrak: Model Picture and Picture merupakan m...,Abstract: The Picture and Picture Model is a l...
362,Lia Yuliantina,pengaruh motivasi terhadap keterampilan menuli...,"Ahmad Jami'ul Amil, S.Pd., M.Pd.","Abdul Rosid, S.Pd., M.Pd.",Penelitian ini merupakan penelitian pendekatan...,This research is a quantitative approach resea...
363,Wasiatun Ni’mah,BENTUK DAN FUNGSI PEMAJASAN PERIBAHASA MADURA ...,"Abdul Rosid, S.Pd, M.Pd","Ika Febriani, S.S, M.Pd.",ABSTRAK\nAbstrak: Peribahasa merupakan kalimat...,ABSTRACT\n Abstract: Proverbs are sentences or...
364,ISTIBSYAROH,"ANALISIS PENGGUNAAN KALIMAT ANALITIS,KONTRADIK...","SULAIMAN, S.Pd., M.Pd","AHMAD JAMIUL AMIL, S.Pd., M.Pd",ABSTRAK\nAbstrak: Penelitian ini mengkaji bent...,ABSTRACT\nAbstract: This study examines the an...

### Pen.Informatika

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def peninfromatika():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 71):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/28/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("peninfromatika.csv", index=False)

    return df

In [ ]:
peninfromatika()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Nurrohmat Hidayatullah Akbar,Pengembangan Game Edukasi 2 Dimensi Untuk Mate...,"Arik Kurniawati, S.Kom. M.T.","Puji Rahayu Ningsih, S.Pd., M.Pd.",Materi struktur dasar algoritma pemrograman me...,The basic structure of the programming algorit...
1,Cholilah,Pengembangan Media Pembelajaran Sistem Bilanga...,"Arik Kurniawati, S.kom., MT.","Wanda Ramansyah, S.Pd., M.Pd","Pada Mata Pelajaran Sistem Komputer, siswa har...","In Computer Systems Subjects, students must co..."
2,TAUFIKUR RAHMAN,PENGARUH MEDIA PEMBELAJARAN E-LEARNING BERBASI...,"MEDIKA RISNASARI, S.ST.,M.T.","MUCHAMAD ARIF, S.PD.,M.PD.",Penelitian ini bertujuan untuk mengetahui peng...,This study aims to determine the effect of lea...
3,Yuliana Wardani,PROFIL BERPIKIR KRITIS SISWA KELAS X TKJ DITIN...,"Puji Rahayu Ningsih,S.Pd.,M.Pd","Sigit Dwi Saputo, S.Pd.,M.Pd",Abstrak\nPenelitian ini bertujuan untuk menget...,Abstract\nThis research aims to know the profi...
4,Deny Prasetyo,PENGEMBANGAN GAME EDUKASI 3D STRUKTUR ALGORITM...,"Arik Kurniawati, S. Kom., M. T.","Sigit Dwi Saputro, S.Pd., M. Pd.",Mata pelajaran pemrograman dasar merupakan sal...,Basic subjects that exist in the Department of...
...,...,...,...,...,...,...
345,Nasiruddin,PENGEMBANGAN PERANGKAT PEMBELAJARAN MODEL PEMB...,"Puji Rahayu Ningsih, S.Pd.,M.Pd","Muhamad Afif Effindi, S.Kom.,M.T",Abstrak\nPenelitian ini bertujuan untuk mengem...,Abstrack\nThis study aims to develop learning ...
346,Samaaul Badi'ah,Analisis Kesalahan Siswa Berdasarkan Prosedur ...,"Puji Rahayu Ningsih, S.Pd., M.Pd.","Medika Risnasari, S.ST., M.T",Siswa mengalami kesulitan dalam materi routing...,Students have difficulty in routing material i...
347,Mahmudy,Pengembangan Media Pembelajaran Trainer Komput...,"Wanda Ramansyah, S.Pd., M.Pd","Muhamad Afif Effindi, S.Kom., M.T",ABSTRAK\n\nPenelitian ini bertujuan untuk menu...,ABSTRACT\n\nThis study aims to foster student ...
348,Yudhistira PIP,Pengembangan Perangkat Rencana Pembelajaran De...,"Ariesta Kartika Sari, S.Si., M.Pd","Wanda Ramansyah, S.Pd., M.Pd",Penelitian ini di latar belakangi oleh perangk...,This research is motivated by the learning too...
349,Nurul Hasanah,PENGEMBANGAN PERANGKAT PEMBELAJARAN KOOPERATIF...,"Ariesta Kartika Sari, S.Si., M.Pd","Laili Cahyani, S.Kom., M.Kom",Penelitian ini bertujuan menghasilkan perangka...,This study aims to produce a TGT cooperative l...

### Pendidikan IPA

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def penipa():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 85):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/29/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("penipa.csv", index=False)

    return df

In [ ]:
penipa()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Anita Enia Urfi,Implementasi Model Pembelajaran Project Based ...,"Mochammad Ahied S.Si., M.Si,","Irsad Rosidi, S.Pd., M.Pd",Penelitian ini bertujuan untuk mengukur tingka...,The aim of this research is to measure level o...
1,Rika Dyanita Sari,PENGARUH PEMBELAJARAN IPA MODEL GUIDED DISCOVE...,"Yunin Hidayati, S.Si., M.Si","Wiwin Puspita Hadi, S.Si., M.Pd.",Penelitian ini bertujuan untuk mengetahui peng...,The aim in this research was to know the influ...
2,Novi Prastiwi,PENGEMBANGAN MAJALAH IPA TERPADU TIPE WEBBED B...,"Yunin Hidayati, S.Si., M.Si","Ana Yuniasti Retno Wulandari, S.Pd., M.Pd",Penelitian dilakukan dengan mengembangkan suat...,"This research developed a product, which was i..."
3,Aden Toyyib,PENGEMBANGAN LEMBAR KERJA SISWABERORIENTASI \n...,"Yunin Hidayati, S.Si., M.Si","Irsad Rosidi, S.Pd., M.Pd",Penelitian ini merupakan penelitian pengembang...,The research aims to know validity of socio sc...
4,ANITA,PENGEMBANGAN PERANGKAT PROBLEM BASED LEARNING ...,"Laila Khamsatul Muharrami, S.Si., M.Si","Ana Yuniasti Retno Wulandari, S.Pd., M.Pd",,
...,...,...,...,...,...,...
412,TRIA MASITAH,Analisis Kemampuan Berpikir Kritis Siswa Mater...,"Ana Yuniasti Retno Wulandari, S.Pd., M.Pd","Wiwin Puspita Hadi, S.Si., M.Pd",Penelitian ini bertujuan untuk mengidentifikas...,This study was aimed at identifying the percen...
413,Indah Sari Mardana,Pengembangan LKS Berbasis Keterampilan Generik...,"Laila khamsatul M, S.Si.,M.Si.","Mochammad Yasir, S.Pd.,M.Pd",Penelitian ini bertujuan untuk mengetahui kela...,"This study aims to determine the feasibility, ..."
414,Kurroti Uyuni,ANALISIS MISKONSEPSI SISWA PADA MATERI KLASIFI...,"Laila Khamsatul Muharrami, S. Si., M. Si","Irsad Rosidi, S.Pd., M. Pd",Penelitian ini bertujuan untuk mengetahui pers...,This study aims to determine the percentage of...
415,Kurrotul Aini,ANALISIS KEMAMPUAN PEMECAHAN MASALAH SISWA PAD...,"Mochammad Ahied, S.Si., M.Si","Mochammad Yasir, S.Pd., M.Pd",Penelitian ini bertujuan untuk menganalisis ke...,The porpouse of this research is to analyze th...
416,SA'ADAH,ANALISIS RATA-RATA KEMAMPUAN BERPIKIR KRITIS S...,"ANA YUNIASTI RETNO WULANDARI, S.PD., M.PD.","AIDA FIKRIYAH, S.PD., M.PD.",Penelitian ini bertujuan untuk mengetahui rata...,This study aims to determine the average resul...

### PGPAUD

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def pgpaud():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 54):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/30/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("pgpaud.csv", index=False)

    return df

In [ ]:
pgpaud()

,penulis,judul,pembimbing_pertama,pembimbing_kedua,abstrak_indo,abstrak_inggris
0,Indri Wulan Suryani,Hubungan Antara Aktivitas Fisik Dengan Kedisip...,"Titin Faridatun Nisa', M.Pd","Yulias Wulani Fajar, M.Pd",Pembelajaran pada anak usia dini dilakukan mel...,ABSTRAK \n \n Learning in early childhood has ...
1,Endang Ratnasari,Efektivitas Penanaman Nilai Agama untuk Membe...,"Titin Faridatun Nisa', M.Pd","Yulias Wulani Fajar, M.Pd",Penanaman nilai agama merupakan salah satu pem...,Applying religion value is one of the more dom...
2,Lischa Dwi Christin Niya Ningrum,PENGARUH METODE DEMONSTRASI TERHADAP PERILAKU ...,"Muhammad Busyro Karim, S.Ag., M.Si.","Dewi Mayangsari, M.Psi",Kesehatan mempunyai pengaruh terhadap pencapai...,Health has an influence on the achievement of ...
3,Siti Herlinah Wifroh,Pengaruh Strategi Meaningful Instructional Des...,"Yulias Wulani Fajar, M.Pd","Titin Faridatun Nisa', S.Pd., M.Pd",Tujuan penelitian ini untuk mengetahui pengaru...,The purpose of this study is to reveal the inf...
4,NUR INAYATUR ROHMATILLAH,AGRESIFITAS ANAK USIA 5-6 TAHUN DENGAN POLA AS...,"Siti Fadjryana Fitroh S.Psi.,MA","Titin Faridatun Nisa' S.Pd.,M.Pd",Tujuan penelitian ini adalah untuk mengatahui ...,The aims of this studyare tounderstand the typ...
...,...,...,...,...,...,...
258,IFTITAHUR RIZQIYAH,PENGASUHAN IBU DENGAN PERAN GANDA PADA ANAK DO...,"Siti Fadjryana Fitroh S.Psi, MA","Dwi Nurhayati Adhani, M.Psi",Ibu memiliki peranan penting dalam pengasuhan ...,Mothers have an important role in caring of ch...
259,Lailatul Izzah,Pengembangan Media Buku Dongeng Fabel Untuk Me...,"Dwi Nurhayati Adhani, S.Psi., M.Psi.","Siti Fadjyana Fitroh, S.Psi., MA.",ABSTRAK\n\nPenelitian ini bertujuan untuk memb...,ABSTRACT\nResearch aims to create and develop ...
260,Ita Iriyanti,Hubungan Metode Bercerita Fabel Dengan Sosial-...,"Dwi Nurhayati Adhani, S.Psi,.M.Psi","Muhammad Busyro karim, S.Ag.,M.Si",Hubungan Metode Bercerita Fabel Dengan Sosial-...,The Relation Of The Fabel Story Method With So...
261,Mega Wulan Sari,PERAN GURU DALAM PENERAPAN SEKOLAH RAMAH ANAK ...,"Dwi Nurhayati Adhani, S.Psi., M.Psi","Muhammad Busyro Karim, S.Ag., M.Si",ABSTRAK\n Penelitian ini bertujuan untuk mende...,ABSTRACT\n This study aims to describe the rol...
262,Defrika Chamilaini,Pengaruh Metode Bercakap - cakap terhadap Kema...,"Busyro Karim,S.Ag, M.Si.","Siti Fadjryana Fitroh, S. Psi., M.A.",Tujuan penelitian ini bertujuan untuk mengetah...,The purpose of this study aims to determine th...

### PPG

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def ppg():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 2):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/38/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("ppg.csv", index=False)

    return df

In [ ]:
ppg()

Empty DataFrame
Columns: [penulis, judul, pembimbing_pertama, pembimbing_kedua, abstrak_indo, abstrak_inggris]
Index: []

## MBKM

### MBKM

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def mbkm():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 2):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/99/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("mbkm.csv", index=False)

    return df

In [ ]:
mbkm()

Empty DataFrame
Columns: [penulis, judul, pembimbing_pertama, pembimbing_kedua, abstrak_indo, abstrak_inggris]
Index: []

## Pascasarjana

### Magister Pendidikan Dasar

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def magisterpendidikandasar():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 2):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/39/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("magisterpendidikandasar.csv", index=False)

    return df

In [ ]:
magisterpendidikandasar()

Empty DataFrame
Columns: [penulis, judul, pembimbing_pertama, pembimbing_kedua, abstrak_indo, abstrak_inggris]
Index: []

### Doktor Pengelolaan Sumber Daya Alam

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def doktorpsda():
    data = {
        "penulis": [],
        "judul": [],
        "pembimbing_pertama": [],
        "pembimbing_kedua": [],
        "abstrak_indo": [],
        "abstrak_inggris": []
    }

    for i in range(1, 2):
        # print(f"📄 Memproses halaman ke-{i}")
        url = "https://pta.trunojoyo.ac.id/c_search/byprod/40/{}".format(i)
        r = requests.get(url)
        request = r.content
        soup = BeautifulSoup(request, "html.parser")
        jurnals = soup.select('li[data-cat="#luxury"]')

        for jurnal in jurnals:
            response = requests.get(jurnal.select_one('a.gray.button')['href'])
            soup1 = BeautifulSoup(response.content, "html.parser")

            isi = soup1.select_one('div#content_journal')

            judul = isi.select_one('a.title').text.strip()
            penulis = isi.find('span', string=lambda t: t and "Penulis" in t).text.split(' : ')[1].strip()
            pembimbing_pertama = isi.find('span', string=lambda t: t and "Dosen Pembimbing I" in t).text.split(' : ')[1].strip()
            pembimbing_kedua = isi.find('span', string=lambda t: t and "Dosen Pembimbing II" in t).text.split(' :')[1].strip()

            abstrak_paragraf = isi.find_all('p', align="justify")
            abstrak_indo = abstrak_paragraf[0].get_text(strip=True) if len(abstrak_paragraf) >= 1 else ''
            abstrak_inggris = abstrak_paragraf[1].get_text(strip=True) if len(abstrak_paragraf) >= 2 else ''

            data["penulis"].append(penulis)
            data["judul"].append(judul)
            data["pembimbing_pertama"].append(pembimbing_pertama)
            data["pembimbing_kedua"].append(pembimbing_kedua)
            data["abstrak_indo"].append(abstrak_indo)
            data["abstrak_inggris"].append(abstrak_inggris)

        time.sleep(1)  # delay 1 detik tiap halaman

    df = pd.DataFrame(data)
    df.to_csv("doktorpsda.csv", index=False)

    return df

In [ ]:
doktorpsda()

Empty DataFrame
Columns: [penulis, judul, pembimbing_pertama, pembimbing_kedua, abstrak_indo, abstrak_inggris]
Index: []